"""
Santa Clara County location reference data for police scanner transcript geocoding.

Every dict maps lowercase lookup keys to canonical geocodable address strings.
This data drives the geocoding pipeline -- missed entries mean missed map pins.
"""

# ---------------------------------------------------------------------------
# Cities and CDPs in Santa Clara County
# ---------------------------------------------------------------------------
SCC_CITIES = [
    "Campbell",
    "Cupertino",
    "Gilroy",
    "Los Altos",
    "Los Altos Hills",
    "Los Gatos",
    "Milpitas",
    "Monte Sereno",
    "Morgan Hill",
    "Mountain View",
    "Palo Alto",
    "San Jose",
    "Santa Clara",
    "Saratoga",
    "Sunnyvale",
    # CDPs / unincorporated
    "Alum Rock",
    "Burbank",
    "Cambrian Park",
    "East Foothills",
    "East San Jose",
    "Fruitdale",
    "Lexington Hills",
    "Loyola",
    "New Almaden",
    "Rancho Rinconada",
    "San Martin",
    "Stanford",
    "West San Jose",
]

# ---------------------------------------------------------------------------
# SCC_STREETS  (~200+ entries)
# Major arterials, boulevards, avenues across all SCC cities.
# Both full name and common shortened versions.
# ---------------------------------------------------------------------------
SCC_STREETS: dict[str, str] = {
    # --- San Jose major arterials ---
    "bascom avenue": "Bascom Avenue, San Jose, CA",
    "bascom ave": "Bascom Avenue, San Jose, CA",
    "bascom": "Bascom Avenue, San Jose, CA",
    "almaden expressway": "Almaden Expressway, San Jose, CA",
    "almaden expwy": "Almaden Expressway, San Jose, CA",
    "almaden": "Almaden Expressway, San Jose, CA",
    "blossom hill road": "Blossom Hill Road, San Jose, CA",
    "blossom hill rd": "Blossom Hill Road, San Jose, CA",
    "blossom hill": "Blossom Hill Road, San Jose, CA",
    "branham lane": "Branham Lane, San Jose, CA",
    "branham": "Branham Lane, San Jose, CA",
    "capitol avenue": "Capitol Avenue, San Jose, CA",
    "capitol ave": "Capitol Avenue, San Jose, CA",
    "coleman avenue": "Coleman Avenue, San Jose, CA",
    "coleman ave": "Coleman Avenue, San Jose, CA",
    "coleman": "Coleman Avenue, San Jose, CA",
    "cottle road": "Cottle Road, San Jose, CA",
    "cottle rd": "Cottle Road, San Jose, CA",
    "cottle": "Cottle Road, San Jose, CA",
    "curtner avenue": "Curtner Avenue, San Jose, CA",
    "curtner ave": "Curtner Avenue, San Jose, CA",
    "curtner": "Curtner Avenue, San Jose, CA",
    "el camino real": "El Camino Real, San Jose, CA",
    "el camino": "El Camino Real, San Jose, CA",
    "foxworthy avenue": "Foxworthy Avenue, San Jose, CA",
    "foxworthy ave": "Foxworthy Avenue, San Jose, CA",
    "foxworthy": "Foxworthy Avenue, San Jose, CA",
    "hamilton avenue": "Hamilton Avenue, San Jose, CA",
    "hamilton ave": "Hamilton Avenue, San Jose, CA",
    "hamilton": "Hamilton Avenue, San Jose, CA",
    "hillsdale avenue": "Hillsdale Avenue, San Jose, CA",
    "hillsdale ave": "Hillsdale Avenue, San Jose, CA",
    "hillsdale": "Hillsdale Avenue, San Jose, CA",
    "jackson avenue": "Jackson Avenue, San Jose, CA",
    "jackson ave": "Jackson Avenue, San Jose, CA",
    "julian street": "Julian Street, San Jose, CA",
    "julian st": "Julian Street, San Jose, CA",
    "julian": "Julian Street, San Jose, CA",
    "king road": "King Road, San Jose, CA",
    "king rd": "King Road, San Jose, CA",
    "king": "King Road, San Jose, CA",
    "leigh avenue": "Leigh Avenue, San Jose, CA",
    "leigh ave": "Leigh Avenue, San Jose, CA",
    "leigh": "Leigh Avenue, San Jose, CA",
    "lincoln avenue": "Lincoln Avenue, San Jose, CA",
    "lincoln ave": "Lincoln Avenue, San Jose, CA",
    "mckee road": "McKee Road, San Jose, CA",
    "mckee rd": "McKee Road, San Jose, CA",
    "mckee": "McKee Road, San Jose, CA",
    "meridian avenue": "Meridian Avenue, San Jose, CA",
    "meridian ave": "Meridian Avenue, San Jose, CA",
    "meridian": "Meridian Avenue, San Jose, CA",
    "monterey road": "Monterey Road, San Jose, CA",
    "monterey rd": "Monterey Road, San Jose, CA",
    "monterey": "Monterey Road, San Jose, CA",
    "moorpark avenue": "Moorpark Avenue, San Jose, CA",
    "moorpark ave": "Moorpark Avenue, San Jose, CA",
    "moorpark": "Moorpark Avenue, San Jose, CA",
    "north 1st street": "North 1st Street, San Jose, CA",
    "north first street": "North 1st Street, San Jose, CA",
    "north first": "North 1st Street, San Jose, CA",
    "n 1st": "North 1st Street, San Jose, CA",
    "ocala avenue": "Ocala Avenue, San Jose, CA",
    "ocala ave": "Ocala Avenue, San Jose, CA",
    "ocala": "Ocala Avenue, San Jose, CA",
    "race street": "Race Street, San Jose, CA",
    "race st": "Race Street, San Jose, CA",
    "san carlos street": "San Carlos Street, San Jose, CA",
    "san carlos st": "San Carlos Street, San Jose, CA",
    "san carlos": "San Carlos Street, San Jose, CA",
    "san fernando street": "San Fernando Street, San Jose, CA",
    "san fernando st": "San Fernando Street, San Jose, CA",
    "san fernando": "San Fernando Street, San Jose, CA",
    "santa clara street": "Santa Clara Street, San Jose, CA",
    "santa clara st": "Santa Clara Street, San Jose, CA",
    "santa teresa boulevard": "Santa Teresa Boulevard, San Jose, CA",
    "santa teresa blvd": "Santa Teresa Boulevard, San Jose, CA",
    "santa teresa": "Santa Teresa Boulevard, San Jose, CA",
    "saratoga avenue": "Saratoga Avenue, San Jose, CA",
    "saratoga ave": "Saratoga Avenue, San Jose, CA",
    "senter road": "Senter Road, San Jose, CA",
    "senter rd": "Senter Road, San Jose, CA",
    "senter": "Senter Road, San Jose, CA",
    "silver creek road": "Silver Creek Road, San Jose, CA",
    "silver creek rd": "Silver Creek Road, San Jose, CA",
    "silver creek": "Silver Creek Road, San Jose, CA",
    "snell avenue": "Snell Avenue, San Jose, CA",
    "snell ave": "Snell Avenue, San Jose, CA",
    "snell": "Snell Avenue, San Jose, CA",
    "stevens creek boulevard": "Stevens Creek Boulevard, San Jose, CA",
    "stevens creek blvd": "Stevens Creek Boulevard, San Jose, CA",
    "stevens creek": "Stevens Creek Boulevard, San Jose, CA",
    "story road": "Story Road, San Jose, CA",
    "story rd": "Story Road, San Jose, CA",
    "story": "Story Road, San Jose, CA",
    "tully road": "Tully Road, San Jose, CA",
    "tully rd": "Tully Road, San Jose, CA",
    "tully": "Tully Road, San Jose, CA",
    "the alameda": "The Alameda, San Jose, CA",
    "alameda": "The Alameda, San Jose, CA",
    "west san carlos street": "West San Carlos Street, San Jose, CA",
    "west san carlos st": "West San Carlos Street, San Jose, CA",
    "west san carlos": "West San Carlos Street, San Jose, CA",
    "white road": "White Road, San Jose, CA",
    "white rd": "White Road, San Jose, CA",
    "white": "White Road, San Jose, CA",
    "yerba buena road": "Yerba Buena Road, San Jose, CA",
    "yerba buena rd": "Yerba Buena Road, San Jose, CA",
    "yerba buena": "Yerba Buena Road, San Jose, CA",
    "alum rock avenue": "Alum Rock Avenue, San Jose, CA",
    "alum rock ave": "Alum Rock Avenue, San Jose, CA",
    "alum rock": "Alum Rock Avenue, San Jose, CA",
    "market street": "Market Street, San Jose, CA",
    "market st": "Market Street, San Jose, CA",
    "park avenue": "Park Avenue, San Jose, CA",
    "park ave": "Park Avenue, San Jose, CA",
    "bird avenue": "Bird Avenue, San Jose, CA",
    "bird ave": "Bird Avenue, San Jose, CA",
    "bird": "Bird Avenue, San Jose, CA",
    "naglee avenue": "Naglee Avenue, San Jose, CA",
    "naglee ave": "Naglee Avenue, San Jose, CA",
    "naglee": "Naglee Avenue, San Jose, CA",
    "mclaughlin avenue": "McLaughlin Avenue, San Jose, CA",
    "mclaughlin ave": "McLaughlin Avenue, San Jose, CA",
    "mclaughlin": "McLaughlin Avenue, San Jose, CA",
    "williams street": "Williams Street, San Jose, CA",
    "williams st": "Williams Street, San Jose, CA",
    "virginia street": "Virginia Street, San Jose, CA",
    "virginia st": "Virginia Street, San Jose, CA",
    "hedding street": "Hedding Street, San Jose, CA",
    "hedding st": "Hedding Street, San Jose, CA",
    "hedding": "Hedding Street, San Jose, CA",
    "taylor street": "Taylor Street, San Jose, CA",
    "taylor st": "Taylor Street, San Jose, CA",
    "auzerais avenue": "Auzerais Avenue, San Jose, CA",
    "auzerais ave": "Auzerais Avenue, San Jose, CA",
    "auzerais": "Auzerais Avenue, San Jose, CA",
    "willow street": "Willow Street, San Jose, CA",
    "willow st": "Willow Street, San Jose, CA",
    "reed street": "Reed Street, San Jose, CA",
    "reed st": "Reed Street, San Jose, CA",
    "keyes street": "Keyes Street, San Jose, CA",
    "keyes st": "Keyes Street, San Jose, CA",
    "keyes": "Keyes Street, San Jose, CA",
    "alma avenue": "Alma Avenue, San Jose, CA",
    "alma ave": "Alma Avenue, San Jose, CA",
    "alma": "Alma Avenue, San Jose, CA",
    "camden avenue": "Camden Avenue, San Jose, CA",
    "camden ave": "Camden Avenue, San Jose, CA",
    "camden": "Camden Avenue, San Jose, CA",
    "union avenue": "Union Avenue, San Jose, CA",
    "union ave": "Union Avenue, San Jose, CA",
    "lundy avenue": "Lundy Avenue, San Jose, CA",
    "lundy ave": "Lundy Avenue, San Jose, CA",
    "lundy": "Lundy Avenue, San Jose, CA",
    "oakland road": "Oakland Road, San Jose, CA",
    "oakland rd": "Oakland Road, San Jose, CA",
    "oakland": "Oakland Road, San Jose, CA",
    "berryessa road": "Berryessa Road, San Jose, CA",
    "berryessa rd": "Berryessa Road, San Jose, CA",
    "berryessa": "Berryessa Road, San Jose, CA",
    "piedmont road": "Piedmont Road, San Jose, CA",
    "piedmont rd": "Piedmont Road, San Jose, CA",
    "piedmont": "Piedmont Road, San Jose, CA",
    "hostetter road": "Hostetter Road, San Jose, CA",
    "hostetter rd": "Hostetter Road, San Jose, CA",
    "hostetter": "Hostetter Road, San Jose, CA",
    "zanker road": "Zanker Road, San Jose, CA",
    "zanker rd": "Zanker Road, San Jose, CA",
    "zanker": "Zanker Road, San Jose, CA",
    "aborn road": "Aborn Road, San Jose, CA",
    "aborn rd": "Aborn Road, San Jose, CA",
    "aborn": "Aborn Road, San Jose, CA",
    "quimby road": "Quimby Road, San Jose, CA",
    "quimby rd": "Quimby Road, San Jose, CA",
    "quimby": "Quimby Road, San Jose, CA",
    "capitol expressway": "Capitol Expressway, San Jose, CA",
    "capitol expwy": "Capitol Expressway, San Jose, CA",
    "capitol exp": "Capitol Expressway, San Jose, CA",
    "san tomas expressway": "San Tomas Expressway, San Jose, CA",
    "san tomas expwy": "San Tomas Expressway, San Jose, CA",
    "san tomas": "San Tomas Expressway, San Jose, CA",
    "lawrence expressway": "Lawrence Expressway, Santa Clara, CA",
    "lawrence expwy": "Lawrence Expressway, Santa Clara, CA",
    "lawrence": "Lawrence Expressway, Santa Clara, CA",
    "great oaks boulevard": "Great Oaks Boulevard, San Jose, CA",
    "great oaks blvd": "Great Oaks Boulevard, San Jose, CA",
    "great oaks": "Great Oaks Boulevard, San Jose, CA",
    "hellyer avenue": "Hellyer Avenue, San Jose, CA",
    "hellyer ave": "Hellyer Avenue, San Jose, CA",
    "hellyer": "Hellyer Avenue, San Jose, CA",
    "gabriel avenue": "Gabriel Avenue, San Jose, CA",
    "gabriel ave": "Gabriel Avenue, San Jose, CA",
    "penitencia creek road": "Penitencia Creek Road, San Jose, CA",
    "penitencia creek rd": "Penitencia Creek Road, San Jose, CA",
    "penitencia creek": "Penitencia Creek Road, San Jose, CA",
    "murphy avenue": "Murphy Avenue, San Jose, CA",
    "murphy ave": "Murphy Avenue, San Jose, CA",

    # --- Downtown SJ numbered streets (1st - 33rd) ---
    "1st street": "1st Street, San Jose, CA",
    "1st st": "1st Street, San Jose, CA",
    "first street": "1st Street, San Jose, CA",
    "first st": "1st Street, San Jose, CA",
    "2nd street": "2nd Street, San Jose, CA",
    "2nd st": "2nd Street, San Jose, CA",
    "second street": "2nd Street, San Jose, CA",
    "second st": "2nd Street, San Jose, CA",
    "3rd street": "3rd Street, San Jose, CA",
    "3rd st": "3rd Street, San Jose, CA",
    "third street": "3rd Street, San Jose, CA",
    "third st": "3rd Street, San Jose, CA",
    "4th street": "4th Street, San Jose, CA",
    "4th st": "4th Street, San Jose, CA",
    "fourth street": "4th Street, San Jose, CA",
    "fourth st": "4th Street, San Jose, CA",
    "5th street": "5th Street, San Jose, CA",
    "5th st": "5th Street, San Jose, CA",
    "fifth street": "5th Street, San Jose, CA",
    "6th street": "6th Street, San Jose, CA",
    "6th st": "6th Street, San Jose, CA",
    "sixth street": "6th Street, San Jose, CA",
    "7th street": "7th Street, San Jose, CA",
    "7th st": "7th Street, San Jose, CA",
    "seventh street": "7th Street, San Jose, CA",
    "8th street": "8th Street, San Jose, CA",
    "8th st": "8th Street, San Jose, CA",
    "eighth street": "8th Street, San Jose, CA",
    "9th street": "9th Street, San Jose, CA",
    "9th st": "9th Street, San Jose, CA",
    "ninth street": "9th Street, San Jose, CA",
    "10th street": "10th Street, San Jose, CA",
    "10th st": "10th Street, San Jose, CA",
    "tenth street": "10th Street, San Jose, CA",
    "11th street": "11th Street, San Jose, CA",
    "11th st": "11th Street, San Jose, CA",
    "12th street": "12th Street, San Jose, CA",
    "12th st": "12th Street, San Jose, CA",
    "13th street": "13th Street, San Jose, CA",
    "13th st": "13th Street, San Jose, CA",
    "14th street": "14th Street, San Jose, CA",
    "14th st": "14th Street, San Jose, CA",
    "15th street": "15th Street, San Jose, CA",
    "15th st": "15th Street, San Jose, CA",
    "16th street": "16th Street, San Jose, CA",
    "16th st": "16th Street, San Jose, CA",
    "17th street": "17th Street, San Jose, CA",
    "17th st": "17th Street, San Jose, CA",
    "18th street": "18th Street, San Jose, CA",
    "18th st": "18th Street, San Jose, CA",
    "19th street": "19th Street, San Jose, CA",
    "19th st": "19th Street, San Jose, CA",
    "20th street": "20th Street, San Jose, CA",
    "20th st": "20th Street, San Jose, CA",
    "21st street": "21st Street, San Jose, CA",
    "21st st": "21st Street, San Jose, CA",
    "22nd street": "22nd Street, San Jose, CA",
    "22nd st": "22nd Street, San Jose, CA",
    "23rd street": "23rd Street, San Jose, CA",
    "23rd st": "23rd Street, San Jose, CA",
    "24th street": "24th Street, San Jose, CA",
    "24th st": "24th Street, San Jose, CA",
    "25th street": "25th Street, San Jose, CA",
    "25th st": "25th Street, San Jose, CA",
    "26th street": "26th Street, San Jose, CA",
    "26th st": "26th Street, San Jose, CA",
    "27th street": "27th Street, San Jose, CA",
    "27th st": "27th Street, San Jose, CA",
    "28th street": "28th Street, San Jose, CA",
    "28th st": "28th Street, San Jose, CA",
    "29th street": "29th Street, San Jose, CA",
    "29th st": "29th Street, San Jose, CA",
    "30th street": "30th Street, San Jose, CA",
    "30th st": "30th Street, San Jose, CA",
    "31st street": "31st Street, San Jose, CA",
    "31st st": "31st Street, San Jose, CA",
    "32nd street": "32nd Street, San Jose, CA",
    "32nd st": "32nd Street, San Jose, CA",
    "33rd street": "33rd Street, San Jose, CA",
    "33rd st": "33rd Street, San Jose, CA",

    # --- Sunnyvale ---
    "el camino real sunnyvale": "El Camino Real, Sunnyvale, CA",
    "mathilda avenue": "Mathilda Avenue, Sunnyvale, CA",
    "mathilda ave": "Mathilda Avenue, Sunnyvale, CA",
    "mathilda": "Mathilda Avenue, Sunnyvale, CA",
    "wolfe road": "Wolfe Road, Sunnyvale, CA",
    "wolfe rd": "Wolfe Road, Sunnyvale, CA",
    "wolfe": "Wolfe Road, Sunnyvale, CA",
    "fair oaks avenue": "Fair Oaks Avenue, Sunnyvale, CA",
    "fair oaks ave": "Fair Oaks Avenue, Sunnyvale, CA",
    "fair oaks": "Fair Oaks Avenue, Sunnyvale, CA",
    "mary avenue": "Mary Avenue, Sunnyvale, CA",
    "mary ave": "Mary Avenue, Sunnyvale, CA",
    "fremont avenue sunnyvale": "Fremont Avenue, Sunnyvale, CA",
    "hollenbeck avenue": "Hollenbeck Avenue, Sunnyvale, CA",
    "hollenbeck ave": "Hollenbeck Avenue, Sunnyvale, CA",
    "java drive": "Java Drive, Sunnyvale, CA",
    "java dr": "Java Drive, Sunnyvale, CA",
    "tasman drive": "Tasman Drive, Sunnyvale, CA",
    "tasman dr": "Tasman Drive, Sunnyvale, CA",
    "tasman": "Tasman Drive, Sunnyvale, CA",
    "caribbean drive": "Caribbean Drive, Sunnyvale, CA",
    "caribbean dr": "Caribbean Drive, Sunnyvale, CA",
    "remington drive": "Remington Drive, Sunnyvale, CA",
    "remington dr": "Remington Drive, Sunnyvale, CA",

    # --- Santa Clara ---
    "great america parkway": "Great America Parkway, Santa Clara, CA",
    "great america pkwy": "Great America Parkway, Santa Clara, CA",
    "great america": "Great America Parkway, Santa Clara, CA",
    "mission college boulevard": "Mission College Boulevard, Santa Clara, CA",
    "mission college blvd": "Mission College Boulevard, Santa Clara, CA",
    "mission college": "Mission College Boulevard, Santa Clara, CA",
    "lafayette street": "Lafayette Street, Santa Clara, CA",
    "lafayette st": "Lafayette Street, Santa Clara, CA",
    "bowers avenue": "Bowers Avenue, Santa Clara, CA",
    "bowers ave": "Bowers Avenue, Santa Clara, CA",
    "bowers": "Bowers Avenue, Santa Clara, CA",
    "scott boulevard": "Scott Boulevard, Santa Clara, CA",
    "scott blvd": "Scott Boulevard, Santa Clara, CA",
    "scott": "Scott Boulevard, Santa Clara, CA",
    "walsh avenue": "Walsh Avenue, Santa Clara, CA",
    "walsh ave": "Walsh Avenue, Santa Clara, CA",
    "monroe street": "Monroe Street, Santa Clara, CA",
    "monroe st": "Monroe Street, Santa Clara, CA",
    "warburton avenue": "Warburton Avenue, Santa Clara, CA",
    "warburton ave": "Warburton Avenue, Santa Clara, CA",
    "el camino real santa clara": "El Camino Real, Santa Clara, CA",
    "patrick henry drive": "Patrick Henry Drive, Santa Clara, CA",
    "patrick henry dr": "Patrick Henry Drive, Santa Clara, CA",
    "agnew road": "Agnew Road, Santa Clara, CA",
    "agnew rd": "Agnew Road, Santa Clara, CA",

    # --- Mountain View ---
    "castro street": "Castro Street, Mountain View, CA",
    "castro st": "Castro Street, Mountain View, CA",
    "castro": "Castro Street, Mountain View, CA",
    "shoreline boulevard": "Shoreline Boulevard, Mountain View, CA",
    "shoreline blvd": "Shoreline Boulevard, Mountain View, CA",
    "shoreline": "Shoreline Boulevard, Mountain View, CA",
    "rengstorff avenue": "Rengstorff Avenue, Mountain View, CA",
    "rengstorff ave": "Rengstorff Avenue, Mountain View, CA",
    "rengstorff": "Rengstorff Avenue, Mountain View, CA",
    "san antonio road": "San Antonio Road, Mountain View, CA",
    "san antonio rd": "San Antonio Road, Mountain View, CA",
    "san antonio": "San Antonio Road, Mountain View, CA",
    "el camino real mountain view": "El Camino Real, Mountain View, CA",
    "central expressway mountain view": "Central Expressway, Mountain View, CA",
    "miramonte avenue": "Miramonte Avenue, Mountain View, CA",
    "miramonte ave": "Miramonte Avenue, Mountain View, CA",
    "miramonte": "Miramonte Avenue, Mountain View, CA",
    "dana street": "Dana Street, Mountain View, CA",
    "dana st": "Dana Street, Mountain View, CA",
    "amphitheatre parkway": "Amphitheatre Parkway, Mountain View, CA",
    "amphitheatre pkwy": "Amphitheatre Parkway, Mountain View, CA",

    # --- Palo Alto ---
    "university avenue": "University Avenue, Palo Alto, CA",
    "university ave": "University Avenue, Palo Alto, CA",
    "university": "University Avenue, Palo Alto, CA",
    "embarcadero road": "Embarcadero Road, Palo Alto, CA",
    "embarcadero rd": "Embarcadero Road, Palo Alto, CA",
    "embarcadero": "Embarcadero Road, Palo Alto, CA",
    "oregon expressway": "Oregon Expressway, Palo Alto, CA",
    "oregon expwy": "Oregon Expressway, Palo Alto, CA",
    "oregon": "Oregon Expressway, Palo Alto, CA",
    "page mill road": "Page Mill Road, Palo Alto, CA",
    "page mill rd": "Page Mill Road, Palo Alto, CA",
    "page mill": "Page Mill Road, Palo Alto, CA",
    "sand hill road": "Sand Hill Road, Palo Alto, CA",
    "sand hill rd": "Sand Hill Road, Palo Alto, CA",
    "sand hill": "Sand Hill Road, Palo Alto, CA",
    "alma street": "Alma Street, Palo Alto, CA",
    "alma st palo alto": "Alma Street, Palo Alto, CA",
    "el camino real palo alto": "El Camino Real, Palo Alto, CA",
    "foothill expressway": "Foothill Expressway, Palo Alto, CA",
    "foothill expwy": "Foothill Expressway, Palo Alto, CA",
    "foothill": "Foothill Expressway, Palo Alto, CA",
    "middlefield road": "Middlefield Road, Palo Alto, CA",
    "middlefield rd": "Middlefield Road, Palo Alto, CA",
    "middlefield": "Middlefield Road, Palo Alto, CA",
    "arastradero road": "Arastradero Road, Palo Alto, CA",
    "arastradero rd": "Arastradero Road, Palo Alto, CA",
    "arastradero": "Arastradero Road, Palo Alto, CA",
    "charleston road": "Charleston Road, Palo Alto, CA",
    "charleston rd": "Charleston Road, Palo Alto, CA",
    "charleston": "Charleston Road, Palo Alto, CA",
    "meadow drive": "Meadow Drive, Palo Alto, CA",
    "meadow dr": "Meadow Drive, Palo Alto, CA",

    # --- Cupertino ---
    "de anza boulevard": "De Anza Boulevard, Cupertino, CA",
    "de anza blvd": "De Anza Boulevard, Cupertino, CA",
    "de anza": "De Anza Boulevard, Cupertino, CA",
    "homestead road": "Homestead Road, Cupertino, CA",
    "homestead rd": "Homestead Road, Cupertino, CA",
    "homestead": "Homestead Road, Cupertino, CA",
    "stelling road": "Stelling Road, Cupertino, CA",
    "stelling rd": "Stelling Road, Cupertino, CA",
    "stelling": "Stelling Road, Cupertino, CA",
    "bollinger road": "Bollinger Road, Cupertino, CA",
    "bollinger rd": "Bollinger Road, Cupertino, CA",
    "bollinger": "Bollinger Road, Cupertino, CA",
    "stevens creek boulevard cupertino": "Stevens Creek Boulevard, Cupertino, CA",
    "stevens creek blvd cupertino": "Stevens Creek Boulevard, Cupertino, CA",
    "prospect road": "Prospect Road, Cupertino, CA",
    "prospect rd": "Prospect Road, Cupertino, CA",
    "prospect": "Prospect Road, Cupertino, CA",
    "miller avenue": "Miller Avenue, Cupertino, CA",
    "miller ave": "Miller Avenue, Cupertino, CA",
    "rainbow drive": "Rainbow Drive, Cupertino, CA",
    "rainbow dr": "Rainbow Drive, Cupertino, CA",

    # --- Milpitas ---
    "calaveras boulevard": "Calaveras Boulevard, Milpitas, CA",
    "calaveras blvd": "Calaveras Boulevard, Milpitas, CA",
    "calaveras": "Calaveras Boulevard, Milpitas, CA",
    "main street milpitas": "Main Street, Milpitas, CA",
    "milpitas boulevard": "Milpitas Boulevard, Milpitas, CA",
    "milpitas blvd": "Milpitas Boulevard, Milpitas, CA",
    "abel street": "Abel Street, Milpitas, CA",
    "abel st": "Abel Street, Milpitas, CA",
    "abel": "Abel Street, Milpitas, CA",
    "montague expressway milpitas": "Montague Expressway, Milpitas, CA",
    "mccarthy boulevard": "McCarthy Boulevard, Milpitas, CA",
    "mccarthy blvd": "McCarthy Boulevard, Milpitas, CA",
    "mccarthy": "McCarthy Boulevard, Milpitas, CA",
    "jacklin road": "Jacklin Road, Milpitas, CA",
    "jacklin rd": "Jacklin Road, Milpitas, CA",
    "jacklin": "Jacklin Road, Milpitas, CA",
    "great mall parkway": "Great Mall Parkway, Milpitas, CA",
    "great mall pkwy": "Great Mall Parkway, Milpitas, CA",

    # --- Campbell ---
    "campbell avenue": "Campbell Avenue, Campbell, CA",
    "campbell ave": "Campbell Avenue, Campbell, CA",
    "winchester boulevard": "Winchester Boulevard, Campbell, CA",
    "winchester blvd": "Winchester Boulevard, Campbell, CA",
    "winchester": "Winchester Boulevard, Campbell, CA",
    "hamilton avenue campbell": "Hamilton Avenue, Campbell, CA",
    "orchard city drive": "Orchard City Drive, Campbell, CA",
    "orchard city dr": "Orchard City Drive, Campbell, CA",

    # --- Los Gatos ---
    "main street los gatos": "Main Street, Los Gatos, CA",
    "los gatos boulevard": "Los Gatos Boulevard, Los Gatos, CA",
    "los gatos blvd": "Los Gatos Boulevard, Los Gatos, CA",
    "los gatos-saratoga road": "Los Gatos-Saratoga Road, Los Gatos, CA",
    "university avenue los gatos": "University Avenue, Los Gatos, CA",
    "lark avenue": "Lark Avenue, Los Gatos, CA",
    "lark ave": "Lark Avenue, Los Gatos, CA",
    "lark": "Lark Avenue, Los Gatos, CA",
    "shannon road": "Shannon Road, Los Gatos, CA",
    "shannon rd": "Shannon Road, Los Gatos, CA",
    "north santa cruz avenue": "North Santa Cruz Avenue, Los Gatos, CA",
    "n santa cruz ave": "North Santa Cruz Avenue, Los Gatos, CA",

    # --- Saratoga ---
    "saratoga-sunnyvale road": "Saratoga-Sunnyvale Road, Saratoga, CA",
    "big basin way": "Big Basin Way, Saratoga, CA",
    "big basin": "Big Basin Way, Saratoga, CA",
    "saratoga-los gatos road": "Saratoga-Los Gatos Road, Saratoga, CA",
    "cox avenue": "Cox Avenue, Saratoga, CA",
    "cox ave": "Cox Avenue, Saratoga, CA",
    "fruitvale avenue": "Fruitvale Avenue, Saratoga, CA",
    "fruitvale ave": "Fruitvale Avenue, Saratoga, CA",
    "fruitvale": "Fruitvale Avenue, Saratoga, CA",
    "quito road": "Quito Road, Saratoga, CA",
    "quito rd": "Quito Road, Saratoga, CA",
    "quito": "Quito Road, Saratoga, CA",

    # --- Los Altos ---
    "main street los altos": "Main Street, Los Altos, CA",
    "san antonio road los altos": "San Antonio Road, Los Altos, CA",
    "el monte road": "El Monte Road, Los Altos, CA",
    "el monte rd": "El Monte Road, Los Altos, CA",
    "el monte": "El Monte Road, Los Altos, CA",
    "loyola drive": "Loyola Drive, Los Altos, CA",
    "loyola dr": "Loyola Drive, Los Altos, CA",
    "springer road": "Springer Road, Los Altos, CA",
    "springer rd": "Springer Road, Los Altos, CA",

    # --- Morgan Hill ---
    "monterey road morgan hill": "Monterey Road, Morgan Hill, CA",
    "dunne avenue": "Dunne Avenue, Morgan Hill, CA",
    "dunne ave": "Dunne Avenue, Morgan Hill, CA",
    "dunne": "Dunne Avenue, Morgan Hill, CA",
    "main avenue morgan hill": "Main Avenue, Morgan Hill, CA",
    "tennant avenue": "Tennant Avenue, Morgan Hill, CA",
    "tennant ave": "Tennant Avenue, Morgan Hill, CA",
    "tennant": "Tennant Avenue, Morgan Hill, CA",
    "cochrane road": "Cochrane Road, Morgan Hill, CA",
    "cochrane rd": "Cochrane Road, Morgan Hill, CA",
    "cochrane": "Cochrane Road, Morgan Hill, CA",
    "butterfield boulevard": "Butterfield Boulevard, Morgan Hill, CA",
    "butterfield blvd": "Butterfield Boulevard, Morgan Hill, CA",
    "butterfield": "Butterfield Boulevard, Morgan Hill, CA",

    # --- Gilroy ---
    "monterey road gilroy": "Monterey Road, Gilroy, CA",
    "first street gilroy": "First Street, Gilroy, CA",
    "10th street gilroy": "10th Street, Gilroy, CA",
    "leavesley road": "Leavesley Road, Gilroy, CA",
    "leavesley rd": "Leavesley Road, Gilroy, CA",
    "leavesley": "Leavesley Road, Gilroy, CA",
    "santa teresa boulevard gilroy": "Santa Teresa Boulevard, Gilroy, CA",
    "hecker pass highway": "Hecker Pass Highway, Gilroy, CA",
    "hecker pass": "Hecker Pass Highway, Gilroy, CA",
    "bolsa road": "Bolsa Road, Gilroy, CA",
    "bolsa rd": "Bolsa Road, Gilroy, CA",
}

# ---------------------------------------------------------------------------
# SCC_EXPRESSWAYS  (~20 entries)
# ---------------------------------------------------------------------------
SCC_EXPRESSWAYS: dict[str, str] = {
    "lawrence expressway": "Lawrence Expressway, Santa Clara, CA",
    "lawrence expwy": "Lawrence Expressway, Santa Clara, CA",
    "lawrence exp": "Lawrence Expressway, Santa Clara, CA",
    "san tomas expressway": "San Tomas Expressway, San Jose, CA",
    "san tomas expwy": "San Tomas Expressway, San Jose, CA",
    "san tomas exp": "San Tomas Expressway, San Jose, CA",
    "capitol expressway": "Capitol Expressway, San Jose, CA",
    "capitol expwy": "Capitol Expressway, San Jose, CA",
    "capitol exp": "Capitol Expressway, San Jose, CA",
    "almaden expressway": "Almaden Expressway, San Jose, CA",
    "almaden expwy": "Almaden Expressway, San Jose, CA",
    "almaden exp": "Almaden Expressway, San Jose, CA",
    "montague expressway": "Montague Expressway, Milpitas, CA",
    "montague expwy": "Montague Expressway, Milpitas, CA",
    "montague exp": "Montague Expressway, Milpitas, CA",
    "montague": "Montague Expressway, Milpitas, CA",
    "central expressway": "Central Expressway, Santa Clara, CA",
    "central expwy": "Central Expressway, Santa Clara, CA",
    "central exp": "Central Expressway, Santa Clara, CA",
    "central": "Central Expressway, Santa Clara, CA",
    "oregon expressway": "Oregon Expressway, Palo Alto, CA",
    "oregon expwy": "Oregon Expressway, Palo Alto, CA",
    "oregon exp": "Oregon Expressway, Palo Alto, CA",
    "foothill expressway": "Foothill Expressway, Los Altos, CA",
    "foothill expwy": "Foothill Expressway, Los Altos, CA",
    "foothill exp": "Foothill Expressway, Los Altos, CA",
}

# ---------------------------------------------------------------------------
# SCC_HIGHWAYS  (~50 entries)
# ---------------------------------------------------------------------------
SCC_HIGHWAYS: dict[str, str] = {
    # US-101 / Bayshore Freeway
    "highway 101": "US-101, San Jose, CA",
    "us 101": "US-101, San Jose, CA",
    "us-101": "US-101, San Jose, CA",
    "101": "US-101, San Jose, CA",
    "bayshore freeway": "US-101, San Jose, CA",
    "bayshore": "US-101, San Jose, CA",
    "101 freeway": "US-101, San Jose, CA",
    "hwy 101": "US-101, San Jose, CA",
    # I-280 / Junipero Serra Freeway
    "interstate 280": "I-280, San Jose, CA",
    "i-280": "I-280, San Jose, CA",
    "i280": "I-280, San Jose, CA",
    "280": "I-280, San Jose, CA",
    "280 freeway": "I-280, San Jose, CA",
    "hwy 280": "I-280, San Jose, CA",
    "junipero serra freeway": "I-280, San Jose, CA",
    "junipero serra": "I-280, San Jose, CA",
    # I-680 / Sinclair Freeway
    "interstate 680": "I-680, San Jose, CA",
    "i-680": "I-680, San Jose, CA",
    "i680": "I-680, San Jose, CA",
    "680": "I-680, San Jose, CA",
    "680 freeway": "I-680, San Jose, CA",
    "hwy 680": "I-680, San Jose, CA",
    # I-880 / Nimitz Freeway
    "interstate 880": "I-880, San Jose, CA",
    "i-880": "I-880, San Jose, CA",
    "i880": "I-880, San Jose, CA",
    "880": "I-880, San Jose, CA",
    "880 freeway": "I-880, San Jose, CA",
    "nimitz freeway": "I-880, San Jose, CA",
    "nimitz": "I-880, San Jose, CA",
    "hwy 880": "I-880, San Jose, CA",
    # CA-85 / West Valley Freeway
    "highway 85": "CA-85, San Jose, CA",
    "ca-85": "CA-85, San Jose, CA",
    "85": "CA-85, San Jose, CA",
    "85 freeway": "CA-85, San Jose, CA",
    "hwy 85": "CA-85, San Jose, CA",
    # CA-87 / Guadalupe Freeway
    "highway 87": "CA-87, San Jose, CA",
    "ca-87": "CA-87, San Jose, CA",
    "87": "CA-87, San Jose, CA",
    "87 freeway": "CA-87, San Jose, CA",
    "hwy 87": "CA-87, San Jose, CA",
    "guadalupe freeway": "CA-87, San Jose, CA",
    "guadalupe parkway": "CA-87, San Jose, CA",
    # CA-17 / Santa Cruz Highway
    "highway 17": "CA-17, San Jose, CA",
    "ca-17": "CA-17, San Jose, CA",
    "17": "CA-17, San Jose, CA",
    "hwy 17": "CA-17, San Jose, CA",
    # CA-237 / Alviso-Milpitas Expressway
    "highway 237": "CA-237, Milpitas, CA",
    "ca-237": "CA-237, Milpitas, CA",
    "237": "CA-237, Milpitas, CA",
    "hwy 237": "CA-237, Milpitas, CA",
    # CA-130 / Mt Hamilton Road
    "highway 130": "CA-130, San Jose, CA",
    "ca-130": "CA-130, San Jose, CA",
    "130": "CA-130, San Jose, CA",
    "mt hamilton road": "CA-130, San Jose, CA",
    "mt hamilton rd": "CA-130, San Jose, CA",
    "mt hamilton": "CA-130, San Jose, CA",
    "mount hamilton": "CA-130, San Jose, CA",
    # CA-9
    "highway 9": "CA-9, Saratoga, CA",
    "ca-9": "CA-9, Saratoga, CA",
    "hwy 9": "CA-9, Saratoga, CA",
    # CA-35 / Skyline Boulevard
    "highway 35": "CA-35, Santa Clara County, CA",
    "ca-35": "CA-35, Santa Clara County, CA",
    "35": "CA-35, Santa Clara County, CA",
    "skyline boulevard": "CA-35, Santa Clara County, CA",
    "skyline blvd": "CA-35, Santa Clara County, CA",
    "skyline": "CA-35, Santa Clara County, CA",
    # CA-152 / Pacheco Pass
    "highway 152": "CA-152, Gilroy, CA",
    "ca-152": "CA-152, Gilroy, CA",
    "152": "CA-152, Gilroy, CA",
    "hwy 152": "CA-152, Gilroy, CA",
    "pacheco pass": "CA-152, Gilroy, CA",
    # CA-82 / El Camino Real (state designation)
    "highway 82": "CA-82, Santa Clara County, CA",
    "ca-82": "CA-82, Santa Clara County, CA",
    "hwy 82": "CA-82, Santa Clara County, CA",
}

# ---------------------------------------------------------------------------
# SCC_HOSPITALS  (~40 entries)
# ---------------------------------------------------------------------------
SCC_HOSPITALS: dict[str, str] = {
    # Valley Medical Center
    "valley medical center": "751 S Bascom Avenue, San Jose, CA 95128",
    "valley medical": "751 S Bascom Avenue, San Jose, CA 95128",
    "valley med": "751 S Bascom Avenue, San Jose, CA 95128",
    "vmc": "751 S Bascom Avenue, San Jose, CA 95128",
    # Regional Medical Center
    "regional medical center": "225 N Jackson Avenue, San Jose, CA 95116",
    "regional medical": "225 N Jackson Avenue, San Jose, CA 95116",
    "regional": "225 N Jackson Avenue, San Jose, CA 95116",
    # Good Samaritan Hospital
    "good samaritan hospital": "2425 Samaritan Drive, San Jose, CA 95124",
    "good samaritan": "2425 Samaritan Drive, San Jose, CA 95124",
    "good sam": "2425 Samaritan Drive, San Jose, CA 95124",
    # O'Connor Hospital
    "o'connor hospital": "2105 Forest Avenue, San Jose, CA 95128",
    "oconnor hospital": "2105 Forest Avenue, San Jose, CA 95128",
    "o'connor": "2105 Forest Avenue, San Jose, CA 95128",
    "oconnor": "2105 Forest Avenue, San Jose, CA 95128",
    # Kaiser San Jose
    "kaiser san jose": "250 Hospital Parkway, San Jose, CA 95119",
    "kaiser santa teresa": "250 Hospital Parkway, San Jose, CA 95119",
    "kaiser south san jose": "250 Hospital Parkway, San Jose, CA 95119",
    # Kaiser Santa Clara
    "kaiser santa clara": "700 Lawrence Expressway, Santa Clara, CA 95051",
    "kaiser lawrence": "700 Lawrence Expressway, Santa Clara, CA 95051",
    "kaiser": "700 Lawrence Expressway, Santa Clara, CA 95051",
    # Stanford Hospital
    "stanford hospital": "300 Pasteur Drive, Stanford, CA 94305",
    "stanford medical center": "300 Pasteur Drive, Stanford, CA 94305",
    "stanford medical": "300 Pasteur Drive, Stanford, CA 94305",
    "stanford health care": "300 Pasteur Drive, Stanford, CA 94305",
    # Lucile Packard Children's Hospital
    "lucile packard": "725 Welch Road, Palo Alto, CA 94304",
    "packard children's": "725 Welch Road, Palo Alto, CA 94304",
    "packard childrens": "725 Welch Road, Palo Alto, CA 94304",
    "stanford children's": "725 Welch Road, Palo Alto, CA 94304",
    # El Camino Hospital Mountain View
    "el camino hospital": "2500 Grant Road, Mountain View, CA 94040",
    "el camino hospital mountain view": "2500 Grant Road, Mountain View, CA 94040",
    "el camino hospital mv": "2500 Grant Road, Mountain View, CA 94040",
    # El Camino Hospital Los Gatos
    "el camino hospital los gatos": "815 Pollard Road, Los Gatos, CA 95032",
    "el camino los gatos": "815 Pollard Road, Los Gatos, CA 95032",
    # Santa Clara Valley Medical Center (alternate name)
    "scvmc": "751 S Bascom Avenue, San Jose, CA 95128",
    # Palo Alto VA
    "va palo alto": "3801 Miranda Avenue, Palo Alto, CA 94304",
    "va hospital": "3801 Miranda Avenue, Palo Alto, CA 94304",
    "veterans hospital": "3801 Miranda Avenue, Palo Alto, CA 94304",
    "palo alto va": "3801 Miranda Avenue, Palo Alto, CA 94304",
    # Saint Louise Regional
    "saint louise regional hospital": "9400 No Name Uno, Gilroy, CA 95020",
    "saint louise": "9400 No Name Uno, Gilroy, CA 95020",
    "st louise": "9400 No Name Uno, Gilroy, CA 95020",
    # Kaiser Milpitas (medical offices)
    "kaiser milpitas": "770 E Calaveras Boulevard, Milpitas, CA 95035",
}

# ---------------------------------------------------------------------------
# SCC_SHOPPING  (~40 entries)
# ---------------------------------------------------------------------------
SCC_SHOPPING: dict[str, str] = {
    # Valley Fair / Westfield
    "valley fair": "2855 Stevens Creek Boulevard, Santa Clara, CA 95050",
    "valley fair mall": "2855 Stevens Creek Boulevard, Santa Clara, CA 95050",
    "westfield valley fair": "2855 Stevens Creek Boulevard, Santa Clara, CA 95050",
    # Santana Row
    "santana row": "377 Santana Row, San Jose, CA 95128",
    "santana": "377 Santana Row, San Jose, CA 95128",
    # Eastridge Mall
    "eastridge": "2200 Eastridge Loop, San Jose, CA 95122",
    "eastridge mall": "2200 Eastridge Loop, San Jose, CA 95122",
    "eastridge center": "2200 Eastridge Loop, San Jose, CA 95122",
    # Oakridge Mall
    "oakridge": "925 Blossom Hill Road, San Jose, CA 95123",
    "oakridge mall": "925 Blossom Hill Road, San Jose, CA 95123",
    "westfield oakridge": "925 Blossom Hill Road, San Jose, CA 95123",
    # Great Mall
    "great mall": "447 Great Mall Drive, Milpitas, CA 95035",
    "great mall milpitas": "447 Great Mall Drive, Milpitas, CA 95035",
    # Stanford Shopping Center
    "stanford shopping center": "660 Stanford Shopping Center, Palo Alto, CA 94304",
    "stanford shopping": "660 Stanford Shopping Center, Palo Alto, CA 94304",
    "stanford mall": "660 Stanford Shopping Center, Palo Alto, CA 94304",
    # Pruneyard
    "pruneyard": "1875 S Bascom Avenue, Campbell, CA 95008",
    "pruneyard shopping center": "1875 S Bascom Avenue, Campbell, CA 95008",
    "the pruneyard": "1875 S Bascom Avenue, Campbell, CA 95008",
    # Westgate Mall
    "westgate": "1600 Saratoga Avenue, San Jose, CA 95129",
    "westgate mall": "1600 Saratoga Avenue, San Jose, CA 95129",
    "westgate center": "1600 Saratoga Avenue, San Jose, CA 95129",
    # Sunnyvale Town Center
    "sunnyvale town center": "125 S Murphy Avenue, Sunnyvale, CA 94086",
    # Cupertino Village
    "cupertino village": "10989 N De Anza Boulevard, Cupertino, CA 95014",
    # Vallco
    "vallco": "10123 N Wolfe Road, Cupertino, CA 95014",
    "vallco mall": "10123 N Wolfe Road, Cupertino, CA 95014",
    "vallco shopping mall": "10123 N Wolfe Road, Cupertino, CA 95014",
    # San Antonio Shopping Center
    "san antonio shopping center": "785 E El Camino Real, Mountain View, CA 94040",
    "san antonio center": "785 E El Camino Real, Mountain View, CA 94040",
    # Gilroy Premium Outlets
    "gilroy outlets": "681 Leavesley Road, Gilroy, CA 95020",
    "gilroy premium outlets": "681 Leavesley Road, Gilroy, CA 95020",
    "premium outlets gilroy": "681 Leavesley Road, Gilroy, CA 95020",
    # Ranch 99 / Milpitas
    "ranch 99": "338 Barber Lane, Milpitas, CA 95035",
    "ranch 99 milpitas": "338 Barber Lane, Milpitas, CA 95035",
    # Mercado
    "mercado": "3111 Mission College Boulevard, Santa Clara, CA 95054",
    # Plant Shopping Center
    "the plant": "411 N Capitol Avenue, San Jose, CA 95133",
    "plant shopping center": "411 N Capitol Avenue, San Jose, CA 95133",
    # Town & Country Village
    "town and country village": "855 El Camino Real, Palo Alto, CA 94301",
    "town and country": "855 El Camino Real, Palo Alto, CA 94301",
    # El Paseo de Saratoga
    "el paseo de saratoga": "1390 Saratoga Avenue, San Jose, CA 95129",
    "el paseo": "1390 Saratoga Avenue, San Jose, CA 95129",
    # Capitol Square
    "capitol square": "Capitol Avenue & McKee Road, San Jose, CA",
    # Milpitas Square
    "milpitas square": "258 S Abel Street, Milpitas, CA 95035",
    # Fry's (historical, now mostly closed but still referenced)
    "fry's electronics": "550 E Brokaw Road, San Jose, CA 95112",
    "fry's": "550 E Brokaw Road, San Jose, CA 95112",
}

# ---------------------------------------------------------------------------
# SCC_PARKS  (~60 entries)
# ---------------------------------------------------------------------------
SCC_PARKS: dict[str, str] = {
    # County Parks
    "alum rock park": "15350 Penitencia Creek Road, San Jose, CA 95127",
    "almaden quicksilver": "21785 Almaden Road, San Jose, CA 95120",
    "almaden quicksilver park": "21785 Almaden Road, San Jose, CA 95120",
    "almaden quicksilver county park": "21785 Almaden Road, San Jose, CA 95120",
    "calero county park": "23205 McKean Road, San Jose, CA 95120",
    "calero park": "23205 McKean Road, San Jose, CA 95120",
    "calero reservoir": "23205 McKean Road, San Jose, CA 95120",
    "joseph d grant county park": "18405 Mt Hamilton Road, San Jose, CA 95140",
    "grant ranch park": "18405 Mt Hamilton Road, San Jose, CA 95140",
    "grant park": "18405 Mt Hamilton Road, San Jose, CA 95140",
    "coyote creek trail": "Coyote Creek Trail, San Jose, CA",
    "coyote creek": "Coyote Creek Trail, San Jose, CA",
    "coyote lake park": "10840 Coyote Lake Road, Gilroy, CA 95020",
    "coyote lake": "10840 Coyote Lake Road, Gilroy, CA 95020",
    "anderson lake county park": "19245 Malaguerra Avenue, Morgan Hill, CA 95037",
    "anderson lake": "19245 Malaguerra Avenue, Morgan Hill, CA 95037",
    "anderson reservoir": "19245 Malaguerra Avenue, Morgan Hill, CA 95037",
    "hellyer county park": "985 Hellyer Avenue, San Jose, CA 95111",
    "hellyer park": "985 Hellyer Avenue, San Jose, CA 95111",
    "vasona lake county park": "333 Blossom Hill Road, Los Gatos, CA 95032",
    "vasona park": "333 Blossom Hill Road, Los Gatos, CA 95032",
    "vasona": "333 Blossom Hill Road, Los Gatos, CA 95032",
    "lexington reservoir": "17770 Alma Bridge Road, Los Gatos, CA 95033",
    "lexington reservoir county park": "17770 Alma Bridge Road, Los Gatos, CA 95033",
    "rancho san antonio": "22500 Cristo Rey Drive, Cupertino, CA 95014",
    "rancho san antonio park": "22500 Cristo Rey Drive, Cupertino, CA 95014",
    "rancho san antonio preserve": "22500 Cristo Rey Drive, Cupertino, CA 95014",
    "ed levin county park": "3100 Calaveras Road, Milpitas, CA 95035",
    "ed levin park": "3100 Calaveras Road, Milpitas, CA 95035",
    "ed levin": "3100 Calaveras Road, Milpitas, CA 95035",
    "sanborn county park": "16055 Sanborn Road, Saratoga, CA 95070",
    "sanborn park": "16055 Sanborn Road, Saratoga, CA 95070",
    "stevens creek county park": "11401 Stevens Canyon Road, Cupertino, CA 95014",
    "stevens creek park": "11401 Stevens Canyon Road, Cupertino, CA 95014",
    "uvas canyon county park": "8515 Croy Road, Morgan Hill, CA 95037",
    "uvas canyon": "8515 Croy Road, Morgan Hill, CA 95037",
    "mount madonna county park": "7850 Pole Line Road, Gilroy, CA 95020",
    "mount madonna park": "7850 Pole Line Road, Gilroy, CA 95020",
    "mount madonna": "7850 Pole Line Road, Gilroy, CA 95020",
    "chesbro reservoir county park": "17895 Oak Glen Avenue, Morgan Hill, CA 95037",
    "chesbro reservoir": "17895 Oak Glen Avenue, Morgan Hill, CA 95037",
    "chitactac-adams heritage county park": "10001 Watsonville Road, Gilroy, CA 95020",
    "field sports county park": "9580 Malech Road, San Jose, CA 95138",
    "field sports park": "9580 Malech Road, San Jose, CA 95138",

    # Open Space Preserves (Midpeninsula)
    "monte bello open space preserve": "Monte Bello Open Space Preserve, Los Altos, CA",
    "monte bello": "Monte Bello Open Space Preserve, Los Altos, CA",
    "russian ridge open space": "Russian Ridge Open Space Preserve, Palo Alto, CA",
    "russian ridge": "Russian Ridge Open Space Preserve, Palo Alto, CA",
    "fremont older open space": "Fremont Older Open Space Preserve, Cupertino, CA",
    "fremont older": "Fremont Older Open Space Preserve, Cupertino, CA",
    "picchetti ranch": "Picchetti Ranch Open Space Preserve, Cupertino, CA",

    # Major City Parks
    "guadalupe river park": "Guadalupe River Park, San Jose, CA",
    "guadalupe river": "Guadalupe River Park, San Jose, CA",
    "kelley park": "1300 Senter Road, San Jose, CA 95112",
    "kelly park": "1300 Senter Road, San Jose, CA 95112",
    "happy hollow park": "1300 Senter Road, San Jose, CA 95112",
    "happy hollow": "1300 Senter Road, San Jose, CA 95112",
    "los gatos creek trail": "Los Gatos Creek Trail, San Jose, CA",
    "los gatos creek": "Los Gatos Creek Trail, San Jose, CA",
    "guadalupe river trail": "Guadalupe River Trail, San Jose, CA",
    "discovery meadow": "180 Woz Way, San Jose, CA 95110",
    "arena green": "Arena Green, San Jose, CA",
    "overfelt gardens": "2145 McKee Road, San Jose, CA 95116",
    "overfelt park": "2145 McKee Road, San Jose, CA 95116",
    "lake cunningham": "2305 S White Road, San Jose, CA 95148",
    "lake cunningham park": "2305 S White Road, San Jose, CA 95148",
    "raging waters": "2333 S White Road, San Jose, CA 95148",
    "watson park": "Watson Park, San Jose, CA",
    "backesto park": "Backesto Park, San Jose, CA",
    "st james park": "St. James Park, San Jose, CA",
    "st. james park": "St. James Park, San Jose, CA",
    "plaza de cesar chavez": "Plaza de Cesar Chavez, San Jose, CA",
    "cesar chavez park": "Plaza de Cesar Chavez, San Jose, CA",
    "shoreline park": "Shoreline Park, Mountain View, CA",
    "baylands park": "Baylands Park, Sunnyvale, CA",
    "mitchell park": "600 E Meadow Drive, Palo Alto, CA 94306",
    "rinconada park": "777 Embarcadero Road, Palo Alto, CA 94301",
}

# ---------------------------------------------------------------------------
# SCC_SCHOOLS  (~100 entries)
# ---------------------------------------------------------------------------
SCC_SCHOOLS: dict[str, str] = {
    # --- Universities / Colleges ---
    "san jose state university": "1 Washington Square, San Jose, CA 95192",
    "san jose state": "1 Washington Square, San Jose, CA 95192",
    "sjsu": "1 Washington Square, San Jose, CA 95192",
    "stanford university": "450 Serra Mall, Stanford, CA 94305",
    "stanford": "450 Serra Mall, Stanford, CA 94305",
    "santa clara university": "500 El Camino Real, Santa Clara, CA 95053",
    "santa clara u": "500 El Camino Real, Santa Clara, CA 95053",
    "scu": "500 El Camino Real, Santa Clara, CA 95053",
    "de anza college": "21250 Stevens Creek Boulevard, Cupertino, CA 95014",
    "de anza": "21250 Stevens Creek Boulevard, Cupertino, CA 95014",
    "foothill college": "12345 El Monte Road, Los Altos Hills, CA 94022",
    "foothill college los altos": "12345 El Monte Road, Los Altos Hills, CA 94022",
    "west valley college": "14000 Fruitvale Avenue, Saratoga, CA 95070",
    "west valley": "14000 Fruitvale Avenue, Saratoga, CA 95070",
    "mission college": "3000 Mission College Boulevard, Santa Clara, CA 95054",
    "mission college santa clara": "3000 Mission College Boulevard, Santa Clara, CA 95054",
    "evergreen valley college": "3095 Yerba Buena Road, San Jose, CA 95135",
    "evergreen valley": "3095 Yerba Buena Road, San Jose, CA 95135",
    "evergreen college": "3095 Yerba Buena Road, San Jose, CA 95135",
    "evc": "3095 Yerba Buena Road, San Jose, CA 95135",
    "san jose city college": "2100 Moorpark Avenue, San Jose, CA 95128",
    "sjcc": "2100 Moorpark Avenue, San Jose, CA 95128",
    "gavilan college": "5055 Santa Teresa Boulevard, Gilroy, CA 95020",
    "gavilan": "5055 Santa Teresa Boulevard, Gilroy, CA 95020",
    "national university san jose": "3031 Tisch Way, San Jose, CA 95128",
    "northwestern polytechnic university": "47671 Westinghouse Drive, Fremont, CA 94539",
    "cogswell polytechnical college": "191 Baypointe Parkway, San Jose, CA 95134",
    "palmer college": "90 E Tasman Drive, San Jose, CA 95134",

    # --- San Jose Unified High Schools ---
    "abraham lincoln high school": "555 Dana Avenue, San Jose, CA 95126",
    "lincoln high school": "555 Dana Avenue, San Jose, CA 95126",
    "lincoln high": "555 Dana Avenue, San Jose, CA 95126",
    "willow glen high school": "2001 Cottle Avenue, San Jose, CA 95125",
    "willow glen high": "2001 Cottle Avenue, San Jose, CA 95125",
    "pioneer high school": "1290 Blossom Hill Road, San Jose, CA 95118",
    "pioneer high": "1290 Blossom Hill Road, San Jose, CA 95118",
    "del mar high school": "1224 Del Mar Avenue, San Jose, CA 95128",
    "del mar high": "1224 Del Mar Avenue, San Jose, CA 95128",
    "gunderson high school": "622 Gaundabert Lane, San Jose, CA 95136",
    "gunderson high": "622 Gaundabert Lane, San Jose, CA 95136",
    "san jose high school": "275 N 24th Street, San Jose, CA 95116",
    "san jose high": "275 N 24th Street, San Jose, CA 95116",
    "san jose high academy": "275 N 24th Street, San Jose, CA 95116",

    # --- East Side Union High School District ---
    "james lick high school": "57 N White Road, San Jose, CA 95127",
    "james lick high": "57 N White Road, San Jose, CA 95127",
    "james lick": "57 N White Road, San Jose, CA 95127",
    "mount pleasant high school": "1750 S White Road, San Jose, CA 95148",
    "mount pleasant high": "1750 S White Road, San Jose, CA 95148",
    "mt pleasant high": "1750 S White Road, San Jose, CA 95148",
    "silver creek high school": "3434 Silver Creek Road, San Jose, CA 95121",
    "silver creek high": "3434 Silver Creek Road, San Jose, CA 95121",
    "evergreen valley high school": "3300 Quimby Road, San Jose, CA 95148",
    "evergreen valley high": "3300 Quimby Road, San Jose, CA 95148",
    "independence high school": "617 N Jackson Avenue, San Jose, CA 95133",
    "independence high": "617 N Jackson Avenue, San Jose, CA 95133",
    "piedmont hills high school": "1377 Piedmont Road, San Jose, CA 95132",
    "piedmont hills high": "1377 Piedmont Road, San Jose, CA 95132",
    "piedmont hills": "1377 Piedmont Road, San Jose, CA 95132",
    "andrew hill high school": "3200 Senter Road, San Jose, CA 95111",
    "andrew hill high": "3200 Senter Road, San Jose, CA 95111",
    "andrew hill": "3200 Senter Road, San Jose, CA 95111",
    "yerba buena high school": "1855 Lucretia Avenue, San Jose, CA 95122",
    "yerba buena high": "1855 Lucretia Avenue, San Jose, CA 95122",
    "oak grove high school": "285 Blossom Hill Road, San Jose, CA 95123",
    "oak grove high": "285 Blossom Hill Road, San Jose, CA 95123",
    "oak grove": "285 Blossom Hill Road, San Jose, CA 95123",
    "overfelt high school": "1835 Cunningham Avenue, San Jose, CA 95122",
    "overfelt high": "1835 Cunningham Avenue, San Jose, CA 95122",
    "w.c. overfelt high": "1835 Cunningham Avenue, San Jose, CA 95122",
    "santa teresa high school": "6150 Snell Avenue, San Jose, CA 95123",
    "santa teresa high": "6150 Snell Avenue, San Jose, CA 95123",

    # --- Campbell Union HSD ---
    "westmont high school": "4805 Westmont Avenue, Campbell, CA 95008",
    "westmont high": "4805 Westmont Avenue, Campbell, CA 95008",
    "branham high school": "1570 Branham Lane, San Jose, CA 95118",
    "branham high": "1570 Branham Lane, San Jose, CA 95118",
    "prospect high school": "18900 Prospect Road, Saratoga, CA 95070",
    "prospect high": "18900 Prospect Road, Saratoga, CA 95070",
    "leigh high school": "5210 Leigh Avenue, San Jose, CA 95124",
    "leigh high": "5210 Leigh Avenue, San Jose, CA 95124",
    "del mar high school campbell": "1224 Del Mar Avenue, San Jose, CA 95128",

    # --- Fremont Union HSD ---
    "fremont high school sunnyvale": "1279 Sunnyvale Saratoga Road, Sunnyvale, CA 94087",
    "fremont high school": "1279 Sunnyvale Saratoga Road, Sunnyvale, CA 94087",
    "fremont high": "1279 Sunnyvale Saratoga Road, Sunnyvale, CA 94087",
    "homestead high school": "21370 Homestead Road, Cupertino, CA 95014",
    "homestead high": "21370 Homestead Road, Cupertino, CA 95014",
    "cupertino high school": "10100 Finch Avenue, Cupertino, CA 95014",
    "cupertino high": "10100 Finch Avenue, Cupertino, CA 95014",
    "monta vista high school": "21840 McClellan Road, Cupertino, CA 95014",
    "monta vista high": "21840 McClellan Road, Cupertino, CA 95014",
    "monta vista": "21840 McClellan Road, Cupertino, CA 95014",
    "lynbrook high school": "1280 Johnson Avenue, San Jose, CA 95129",
    "lynbrook high": "1280 Johnson Avenue, San Jose, CA 95129",
    "lynbrook": "1280 Johnson Avenue, San Jose, CA 95129",

    # --- Mountain View / Los Altos ---
    "mountain view high school": "3535 Truman Avenue, Mountain View, CA 94040",
    "mountain view high": "3535 Truman Avenue, Mountain View, CA 94040",
    "los altos high school": "201 Almond Avenue, Los Altos, CA 94022",
    "los altos high": "201 Almond Avenue, Los Altos, CA 94022",

    # --- Palo Alto Unified ---
    "palo alto high school": "50 Embarcadero Road, Palo Alto, CA 94301",
    "palo alto high": "50 Embarcadero Road, Palo Alto, CA 94301",
    "paly": "50 Embarcadero Road, Palo Alto, CA 94301",
    "henry gunn high school": "780 Arastradero Road, Palo Alto, CA 94306",
    "gunn high school": "780 Arastradero Road, Palo Alto, CA 94306",
    "gunn high": "780 Arastradero Road, Palo Alto, CA 94306",
    "gunn": "780 Arastradero Road, Palo Alto, CA 94306",

    # --- Other ---
    "milpitas high school": "1285 Escuela Parkway, Milpitas, CA 95035",
    "milpitas high": "1285 Escuela Parkway, Milpitas, CA 95035",
    "los gatos high school": "20 High School Court, Los Gatos, CA 95030",
    "los gatos high": "20 High School Court, Los Gatos, CA 95030",
    "saratoga high school": "20300 Herriman Avenue, Saratoga, CA 95070",
    "saratoga high": "20300 Herriman Avenue, Saratoga, CA 95070",
    "live oak high school": "1505 E Main Avenue, Morgan Hill, CA 95037",
    "live oak high": "1505 E Main Avenue, Morgan Hill, CA 95037",
    "ann sobrato high school": "401 Burnett Avenue, Morgan Hill, CA 95037",
    "sobrato high school": "401 Burnett Avenue, Morgan Hill, CA 95037",
    "sobrato high": "401 Burnett Avenue, Morgan Hill, CA 95037",
    "gilroy high school": "750 W 10th Street, Gilroy, CA 95020",
    "gilroy high": "750 W 10th Street, Gilroy, CA 95020",
    "christopher high school": "850 Day Road, Gilroy, CA 95020",
    "christopher high": "850 Day Road, Gilroy, CA 95020",
    "leland high school": "6677 Camden Avenue, San Jose, CA 95120",
    "leland high": "6677 Camden Avenue, San Jose, CA 95120",
    "leland": "6677 Camden Avenue, San Jose, CA 95120",
    "presentation high school": "2281 Plummer Avenue, San Jose, CA 95125",
    "presentation high": "2281 Plummer Avenue, San Jose, CA 95125",
    "bellarmine college prep": "960 W Hedding Street, San Jose, CA 95126",
    "bellarmine": "960 W Hedding Street, San Jose, CA 95126",
    "valley christian high school": "100 Skyway Drive, San Jose, CA 95111",
    "valley christian": "100 Skyway Drive, San Jose, CA 95111",
    "archbishop mitty high school": "5000 Mitty Way, San Jose, CA 95129",
    "archbishop mitty": "5000 Mitty Way, San Jose, CA 95129",
    "mitty high": "5000 Mitty Way, San Jose, CA 95129",
    "mitty": "5000 Mitty Way, San Jose, CA 95129",
}

# ---------------------------------------------------------------------------
# SCC_TRANSIT  (~80 entries)
# ---------------------------------------------------------------------------
SCC_TRANSIT: dict[str, str] = {
    # --- Caltrain Stations ---
    "caltrain palo alto": "95 University Avenue, Palo Alto, CA 94301",
    "palo alto caltrain": "95 University Avenue, Palo Alto, CA 94301",
    "caltrain mountain view": "600 W Evelyn Avenue, Mountain View, CA 94041",
    "mountain view caltrain": "600 W Evelyn Avenue, Mountain View, CA 94041",
    "caltrain sunnyvale": "121 W Evelyn Avenue, Sunnyvale, CA 94086",
    "sunnyvale caltrain": "121 W Evelyn Avenue, Sunnyvale, CA 94086",
    "caltrain santa clara": "1001 Railroad Avenue, Santa Clara, CA 95050",
    "santa clara caltrain": "1001 Railroad Avenue, Santa Clara, CA 95050",
    "caltrain san jose diridon": "65 Cahill Street, San Jose, CA 95110",
    "diridon caltrain": "65 Cahill Street, San Jose, CA 95110",
    "diridon station": "65 Cahill Street, San Jose, CA 95110",
    "diridon": "65 Cahill Street, San Jose, CA 95110",
    "caltrain college park": "College Park Station, San Jose, CA",
    "college park caltrain": "College Park Station, San Jose, CA",
    "caltrain san antonio": "San Antonio Caltrain Station, Mountain View, CA",
    "san antonio caltrain": "San Antonio Caltrain Station, Mountain View, CA",
    "caltrain california avenue": "California Avenue Caltrain Station, Palo Alto, CA",
    "california avenue caltrain": "California Avenue Caltrain Station, Palo Alto, CA",
    "cal ave caltrain": "California Avenue Caltrain Station, Palo Alto, CA",
    "caltrain lawrence": "Lawrence Caltrain Station, Sunnyvale, CA",
    "lawrence caltrain": "Lawrence Caltrain Station, Sunnyvale, CA",
    "caltrain capitol": "Capitol Caltrain Station, San Jose, CA",
    "capitol caltrain": "Capitol Caltrain Station, San Jose, CA",
    "caltrain tamien": "Tamien Caltrain Station, San Jose, CA",
    "tamien caltrain": "Tamien Caltrain Station, San Jose, CA",
    "tamien station": "Tamien Station, San Jose, CA",
    "tamien": "Tamien Station, San Jose, CA",
    "caltrain blossom hill": "Blossom Hill Caltrain Station, San Jose, CA",
    "blossom hill caltrain": "Blossom Hill Caltrain Station, San Jose, CA",
    "caltrain morgan hill": "Morgan Hill Caltrain Station, Morgan Hill, CA",
    "morgan hill caltrain": "Morgan Hill Caltrain Station, Morgan Hill, CA",
    "caltrain gilroy": "Gilroy Caltrain Station, Gilroy, CA",
    "gilroy caltrain": "Gilroy Caltrain Station, Gilroy, CA",

    # --- VTA Light Rail: Mountain View - Winchester line (Orange Line) ---
    "mountain view station": "Mountain View VTA Station, Mountain View, CA",
    "mountain view vta": "Mountain View VTA Station, Mountain View, CA",
    "whisman station": "Whisman VTA Station, Mountain View, CA",
    "whisman vta": "Whisman VTA Station, Mountain View, CA",
    "middlefield station": "Middlefield VTA Station, Mountain View, CA",
    "middlefield vta": "Middlefield VTA Station, Mountain View, CA",
    "bayshore nasa station": "Bayshore/NASA VTA Station, Sunnyvale, CA",
    "bayshore nasa": "Bayshore/NASA VTA Station, Sunnyvale, CA",
    "moffett park station": "Moffett Park VTA Station, Sunnyvale, CA",
    "moffett park vta": "Moffett Park VTA Station, Sunnyvale, CA",
    "lockheed martin station": "Lockheed Martin VTA Station, Sunnyvale, CA",
    "lockheed martin vta": "Lockheed Martin VTA Station, Sunnyvale, CA",
    "borregas station": "Borregas VTA Station, Sunnyvale, CA",
    "borregas vta": "Borregas VTA Station, Sunnyvale, CA",
    "crossman station": "Crossman VTA Station, Sunnyvale, CA",
    "crossman vta": "Crossman VTA Station, Sunnyvale, CA",
    "fair oaks station": "Fair Oaks VTA Station, Sunnyvale, CA",
    "fair oaks vta": "Fair Oaks VTA Station, Sunnyvale, CA",
    "vienna station": "Vienna VTA Station, Sunnyvale, CA",
    "vienna vta": "Vienna VTA Station, Sunnyvale, CA",
    "reamwood station": "Reamwood VTA Station, Sunnyvale, CA",
    "reamwood vta": "Reamwood VTA Station, Sunnyvale, CA",
    "old ironsides station": "Old Ironsides VTA Station, Santa Clara, CA",
    "old ironsides vta": "Old Ironsides VTA Station, Santa Clara, CA",
    "great america station": "Great America VTA Station, Santa Clara, CA",
    "great america vta": "Great America VTA Station, Santa Clara, CA",
    "lick mill station": "Lick Mill VTA Station, Santa Clara, CA",
    "lick mill vta": "Lick Mill VTA Station, Santa Clara, CA",
    "champion station": "Champion VTA Station, Santa Clara, CA",
    "champion vta": "Champion VTA Station, Santa Clara, CA",
    "tasman station": "Tasman VTA Station, San Jose, CA",
    "tasman vta": "Tasman VTA Station, San Jose, CA",
    "orchard station": "Orchard VTA Station, San Jose, CA",
    "orchard vta": "Orchard VTA Station, San Jose, CA",
    "river oaks station": "River Oaks VTA Station, San Jose, CA",
    "river oaks vta": "River Oaks VTA Station, San Jose, CA",
    "component station": "Component VTA Station, San Jose, CA",
    "component vta": "Component VTA Station, San Jose, CA",
    "bonaventura station": "Bonaventura VTA Station, San Jose, CA",
    "bonaventura vta": "Bonaventura VTA Station, San Jose, CA",
    "metro ohlone station": "Metro/Ohlone VTA Station, San Jose, CA",
    "metro ohlone vta": "Metro/Ohlone VTA Station, San Jose, CA",
    "fruitdale station": "Fruitdale VTA Station, San Jose, CA",
    "fruitdale vta": "Fruitdale VTA Station, San Jose, CA",
    "race station": "Race VTA Station, San Jose, CA",
    "race vta": "Race VTA Station, San Jose, CA",
    "bascom station": "Bascom VTA Station, San Jose, CA",
    "bascom vta": "Bascom VTA Station, San Jose, CA",
    "hamilton station": "Hamilton VTA Station, Campbell, CA",
    "hamilton vta": "Hamilton VTA Station, Campbell, CA",
    "campbell station": "Campbell VTA Station, Campbell, CA",
    "campbell vta": "Campbell VTA Station, Campbell, CA",
    "winchester station": "Winchester VTA Station, Campbell, CA",
    "winchester vta": "Winchester VTA Station, Campbell, CA",

    # --- VTA Light Rail: Alum Rock - Santa Teresa line (Blue/Green) ---
    "convention center station": "Convention Center VTA Station, San Jose, CA",
    "convention center vta": "Convention Center VTA Station, San Jose, CA",
    "san jose convention center station": "Convention Center VTA Station, San Jose, CA",
    "paseo de san antonio station": "Paseo de San Antonio VTA Station, San Jose, CA",
    "paseo de san antonio vta": "Paseo de San Antonio VTA Station, San Jose, CA",
    "san fernando station": "San Fernando VTA Station, San Jose, CA",
    "san fernando vta": "San Fernando VTA Station, San Jose, CA",
    "st james station": "St. James VTA Station, San Jose, CA",
    "st james vta": "St. James VTA Station, San Jose, CA",
    "japantown ayer station": "Japantown/Ayer VTA Station, San Jose, CA",
    "japantown ayer vta": "Japantown/Ayer VTA Station, San Jose, CA",
    "japantown station": "Japantown/Ayer VTA Station, San Jose, CA",
    "civic center station": "Civic Center VTA Station, San Jose, CA",
    "civic center vta": "Civic Center VTA Station, San Jose, CA",
    "gish station": "Gish VTA Station, San Jose, CA",
    "gish vta": "Gish VTA Station, San Jose, CA",
    "karina court station": "Karina Court VTA Station, San Jose, CA",
    "karina court vta": "Karina Court VTA Station, San Jose, CA",
    "metro airport station": "Metro/Airport VTA Station, San Jose, CA",
    "metro airport vta": "Metro/Airport VTA Station, San Jose, CA",
    "milpitas station": "Milpitas BART/VTA Station, Milpitas, CA",
    "milpitas bart": "Milpitas BART/VTA Station, Milpitas, CA",
    "milpitas vta": "Milpitas BART/VTA Station, Milpitas, CA",
    "berryessa bart": "Berryessa BART Station, San Jose, CA",
    "berryessa station": "Berryessa BART Station, San Jose, CA",
    "berryessa vta": "Berryessa BART Station, San Jose, CA",
    "alum rock bart": "Alum Rock BART Station, San Jose, CA",
    "alum rock station": "Alum Rock BART Station, San Jose, CA",
    "virginia station": "Virginia VTA Station, San Jose, CA",
    "virginia vta": "Virginia VTA Station, San Jose, CA",
    "curtner station": "Curtner VTA Station, San Jose, CA",
    "curtner vta": "Curtner VTA Station, San Jose, CA",
    "capitol station": "Capitol VTA Station, San Jose, CA",
    "capitol vta": "Capitol VTA Station, San Jose, CA",
    "branham station": "Branham VTA Station, San Jose, CA",
    "branham vta": "Branham VTA Station, San Jose, CA",
    "ohlone chynoweth station": "Ohlone/Chynoweth VTA Station, San Jose, CA",
    "ohlone chynoweth vta": "Ohlone/Chynoweth VTA Station, San Jose, CA",
    "oakridge station": "Oakridge VTA Station, San Jose, CA",
    "oakridge vta": "Oakridge VTA Station, San Jose, CA",
    "snell station": "Snell VTA Station, San Jose, CA",
    "snell vta": "Snell VTA Station, San Jose, CA",
    "cottle station": "Cottle VTA Station, San Jose, CA",
    "cottle vta": "Cottle VTA Station, San Jose, CA",
    "blossom hill station": "Blossom Hill VTA Station, San Jose, CA",
    "blossom hill vta": "Blossom Hill VTA Station, San Jose, CA",
    "santa teresa station": "Santa Teresa VTA Station, San Jose, CA",
    "santa teresa vta": "Santa Teresa VTA Station, San Jose, CA",

    # --- Key bus transfer points ---
    "eastridge transit center": "Eastridge Transit Center, San Jose, CA",
    "eastridge transit": "Eastridge Transit Center, San Jose, CA",
    "milpitas transit center": "Milpitas Transit Center, Milpitas, CA",
    "milpitas transit": "Milpitas Transit Center, Milpitas, CA",
    "palo alto transit center": "Palo Alto Transit Center, Palo Alto, CA",
    "palo alto transit": "Palo Alto Transit Center, Palo Alto, CA",
    "sunnyvale transit center": "Sunnyvale Transit Center, Sunnyvale, CA",
    "sunnyvale transit": "Sunnyvale Transit Center, Sunnyvale, CA",
}

# ---------------------------------------------------------------------------
# SCC_PUBLIC_SAFETY  (~80 entries)
# ---------------------------------------------------------------------------
SCC_PUBLIC_SAFETY: dict[str, str] = {
    # --- SJPD ---
    "sjpd headquarters": "201 W Mission Street, San Jose, CA 95110",
    "sjpd hq": "201 W Mission Street, San Jose, CA 95110",
    "san jose police department": "201 W Mission Street, San Jose, CA 95110",
    "san jose police headquarters": "201 W Mission Street, San Jose, CA 95110",
    "sjpd western division": "1580 Naglee Avenue, San Jose, CA 95126",
    "sjpd western": "1580 Naglee Avenue, San Jose, CA 95126",
    "western division": "1580 Naglee Avenue, San Jose, CA 95126",
    "sjpd southern division": "3333 Monterey Road, San Jose, CA 95111",
    "sjpd southern": "3333 Monterey Road, San Jose, CA 95111",
    "southern division": "3333 Monterey Road, San Jose, CA 95111",
    "sjpd foothill division": "3281 E Hills Drive, San Jose, CA 95127",
    "sjpd foothill": "3281 E Hills Drive, San Jose, CA 95127",
    "foothill division": "3281 E Hills Drive, San Jose, CA 95127",
    "sjpd bureau of field operations": "201 W Mission Street, San Jose, CA 95110",

    # --- Other city PDs ---
    "santa clara police department": "601 El Camino Real, Santa Clara, CA 95050",
    "santa clara pd": "601 El Camino Real, Santa Clara, CA 95050",
    "sunnyvale dps": "700 All America Way, Sunnyvale, CA 94086",
    "sunnyvale department of public safety": "700 All America Way, Sunnyvale, CA 94086",
    "sunnyvale police": "700 All America Way, Sunnyvale, CA 94086",
    "mountain view police department": "1000 Villa Street, Mountain View, CA 94041",
    "mountain view pd": "1000 Villa Street, Mountain View, CA 94041",
    "mvpd": "1000 Villa Street, Mountain View, CA 94041",
    "palo alto police department": "275 Forest Avenue, Palo Alto, CA 94301",
    "palo alto pd": "275 Forest Avenue, Palo Alto, CA 94301",
    "papd": "275 Forest Avenue, Palo Alto, CA 94301",
    "milpitas police department": "1275 N Milpitas Boulevard, Milpitas, CA 95035",
    "milpitas pd": "1275 N Milpitas Boulevard, Milpitas, CA 95035",
    "campbell police department": "70 N 1st Street, Campbell, CA 95008",
    "campbell pd": "70 N 1st Street, Campbell, CA 95008",
    "los gatos police department": "110 E Main Street, Los Gatos, CA 95030",
    "los gatos pd": "110 E Main Street, Los Gatos, CA 95030",
    "morgan hill police department": "16200 Vineyard Boulevard, Morgan Hill, CA 95037",
    "morgan hill pd": "16200 Vineyard Boulevard, Morgan Hill, CA 95037",
    "gilroy police department": "7301 Hanna Street, Gilroy, CA 95020",
    "gilroy pd": "7301 Hanna Street, Gilroy, CA 95020",
    "cupertino sheriff substation": "10455 De Anza Boulevard, Cupertino, CA 95014",
    "saratoga sheriff substation": "14580 Big Basin Way, Saratoga, CA 95070",
    "los altos police department": "1 N San Antonio Road, Los Altos, CA 94022",
    "los altos pd": "1 N San Antonio Road, Los Altos, CA 94022",

    # --- Sheriff / County ---
    "santa clara county sheriff": "55 W Younger Avenue, San Jose, CA 95110",
    "scc sheriff": "55 W Younger Avenue, San Jose, CA 95110",
    "county sheriff": "55 W Younger Avenue, San Jose, CA 95110",
    "sheriffs office": "55 W Younger Avenue, San Jose, CA 95110",

    # --- Jails ---
    "main jail": "150 W Hedding Street, San Jose, CA 95110",
    "main jail north": "150 W Hedding Street, San Jose, CA 95110",
    "elmwood correctional facility": "701 S Abel Street, Milpitas, CA 95035",
    "elmwood jail": "701 S Abel Street, Milpitas, CA 95035",
    "elmwood": "701 S Abel Street, Milpitas, CA 95035",

    # --- Courthouses ---
    "santa clara county superior court": "191 N 1st Street, San Jose, CA 95113",
    "superior court san jose": "191 N 1st Street, San Jose, CA 95113",
    "downtown superior court": "191 N 1st Street, San Jose, CA 95113",
    "hall of justice": "190 W Hedding Street, San Jose, CA 95110",
    "hall of justice san jose": "190 W Hedding Street, San Jose, CA 95110",
    "palo alto courthouse": "270 Grant Avenue, Palo Alto, CA 94306",
    "morgan hill courthouse": "233 W Dunne Avenue, Morgan Hill, CA 95037",
    "family justice center": "381 S 1st Street, San Jose, CA 95113",

    # --- Fire Stations (selected major stations) ---
    "san jose fire station 1": "225 N Market Street, San Jose, CA 95110",
    "sjfd station 1": "225 N Market Street, San Jose, CA 95110",
    "fire station 1": "225 N Market Street, San Jose, CA 95110",
    "san jose fire station 7": "800 Emory Street, San Jose, CA 95126",
    "sjfd station 7": "800 Emory Street, San Jose, CA 95126",
    "san jose fire station 30": "3030 Senter Road, San Jose, CA 95111",
    "sjfd station 30": "3030 Senter Road, San Jose, CA 95111",
    "san jose fire station 35": "5960 Cahalan Avenue, San Jose, CA 95123",
    "sjfd station 35": "5960 Cahalan Avenue, San Jose, CA 95123",
    "santa clara fire station 1": "1300 Franklin Street, Santa Clara, CA 95050",
    "sunnyvale fire station 1": "171 N Mathilda Avenue, Sunnyvale, CA 94086",
    "mountain view fire station 1": "251 S Shoreline Boulevard, Mountain View, CA 94041",
    "palo alto fire station 1": "301 Alma Street, Palo Alto, CA 94301",
    "milpitas fire station 1": "777 S Main Street, Milpitas, CA 95035",
    "campbell fire station 1": "595 W Campbell Avenue, Campbell, CA 95008",
    "los gatos fire station 1": "306 University Avenue, Los Gatos, CA 95030",

    # --- CHP ---
    "chp san jose": "2025 Gateway Place, San Jose, CA 95110",
    "california highway patrol san jose": "2025 Gateway Place, San Jose, CA 95110",
    "chp san jose office": "2025 Gateway Place, San Jose, CA 95110",
    "chp gilroy": "378 1st Street, Gilroy, CA 95020",

    # --- County buildings ---
    "county government center": "70 W Hedding Street, San Jose, CA 95110",
    "county center": "70 W Hedding Street, San Jose, CA 95110",
    "medical examiner": "850 Thornton Way, San Jose, CA 95128",
    "me office": "850 Thornton Way, San Jose, CA 95128",
    "coroner's office": "850 Thornton Way, San Jose, CA 95128",
    "coroners office": "850 Thornton Way, San Jose, CA 95128",
}

# ---------------------------------------------------------------------------
# SCC_LANDMARKS  (~50 entries)
# ---------------------------------------------------------------------------
SCC_LANDMARKS: dict[str, str] = {
    # Major venues
    "sap center": "525 W Santa Clara Street, San Jose, CA 95113",
    "sap center at san jose": "525 W Santa Clara Street, San Jose, CA 95113",
    "shark tank": "525 W Santa Clara Street, San Jose, CA 95113",
    "hp pavilion": "525 W Santa Clara Street, San Jose, CA 95113",
    "levis stadium": "4900 Marie P DeBartolo Way, Santa Clara, CA 95054",
    "levi's stadium": "4900 Marie P DeBartolo Way, Santa Clara, CA 95054",
    "49ers stadium": "4900 Marie P DeBartolo Way, Santa Clara, CA 95054",
    "paypal park": "1123 Coleman Avenue, San Jose, CA 95110",
    "earthquakes stadium": "1123 Coleman Avenue, San Jose, CA 95110",
    "avaya stadium": "1123 Coleman Avenue, San Jose, CA 95110",
    "san jose convention center": "150 W San Carlos Street, San Jose, CA 95113",
    "convention center": "150 W San Carlos Street, San Jose, CA 95113",
    "san jose mcenery convention center": "150 W San Carlos Street, San Jose, CA 95113",
    "mcenery convention center": "150 W San Carlos Street, San Jose, CA 95113",
    "center for the performing arts": "255 S Almaden Boulevard, San Jose, CA 95113",
    "cpa san jose": "255 S Almaden Boulevard, San Jose, CA 95113",
    "california theatre": "345 S 1st Street, San Jose, CA 95113",
    "san jose civic": "135 W San Carlos Street, San Jose, CA 95113",

    # Airports
    "san jose international airport": "1701 Airport Boulevard, San Jose, CA 95110",
    "sjc": "1701 Airport Boulevard, San Jose, CA 95110",
    "san jose airport": "1701 Airport Boulevard, San Jose, CA 95110",
    "mineta san jose": "1701 Airport Boulevard, San Jose, CA 95110",
    "norman y. mineta san jose international airport": "1701 Airport Boulevard, San Jose, CA 95110",
    "moffett field": "Moffett Federal Airfield, Mountain View, CA 94035",
    "moffett federal airfield": "Moffett Federal Airfield, Mountain View, CA 94035",
    "moffett": "Moffett Federal Airfield, Mountain View, CA 94035",
    "nasa ames": "Moffett Federal Airfield, Mountain View, CA 94035",
    "nasa ames research center": "Moffett Federal Airfield, Mountain View, CA 94035",
    "reid hillview airport": "2500 Cunningham Avenue, San Jose, CA 95148",
    "reid hillview": "2500 Cunningham Avenue, San Jose, CA 95148",
    "south county airport": "13030 Murphy Avenue, San Martin, CA 95046",
    "san martin airport": "13030 Murphy Avenue, San Martin, CA 95046",
    "palo alto airport": "1925 Embarcadero Road, Palo Alto, CA 94303",

    # Tech campuses
    "apple park": "1 Apple Park Way, Cupertino, CA 95014",
    "apple campus": "1 Apple Park Way, Cupertino, CA 95014",
    "apple infinite loop": "1 Infinite Loop, Cupertino, CA 95014",
    "infinite loop": "1 Infinite Loop, Cupertino, CA 95014",
    "googleplex": "1600 Amphitheatre Parkway, Mountain View, CA 94043",
    "google campus": "1600 Amphitheatre Parkway, Mountain View, CA 94043",
    "google mountain view": "1600 Amphitheatre Parkway, Mountain View, CA 94043",
    "meta campus": "1 Hacker Way, Menlo Park, CA 94025",
    "nvidia headquarters": "2788 San Tomas Expressway, Santa Clara, CA 95051",
    "nvidia hq": "2788 San Tomas Expressway, Santa Clara, CA 95051",
    "intel santa clara": "2200 Mission College Boulevard, Santa Clara, CA 95054",
    "intel headquarters": "2200 Mission College Boulevard, Santa Clara, CA 95054",

    # Theme parks
    "great america": "4701 Great America Parkway, Santa Clara, CA 95054",
    "california's great america": "4701 Great America Parkway, Santa Clara, CA 95054",
    "great america theme park": "4701 Great America Parkway, Santa Clara, CA 95054",

    # Museums / Cultural
    "tech interactive": "201 S Market Street, San Jose, CA 95113",
    "the tech": "201 S Market Street, San Jose, CA 95113",
    "tech museum": "201 S Market Street, San Jose, CA 95113",
    "san jose museum of art": "110 S Market Street, San Jose, CA 95113",
    "childrens discovery museum": "180 Woz Way, San Jose, CA 95110",
    "children's discovery museum": "180 Woz Way, San Jose, CA 95110",
    "rosicrucian museum": "1660 Park Avenue, San Jose, CA 95191",
    "rosicrucian": "1660 Park Avenue, San Jose, CA 95191",
    "winchester mystery house": "525 S Winchester Boulevard, San Jose, CA 95128",
    "winchester house": "525 S Winchester Boulevard, San Jose, CA 95128",
    "winchester mansion": "525 S Winchester Boulevard, San Jose, CA 95128",

    # Other landmarks
    "san jose city hall": "200 E Santa Clara Street, San Jose, CA 95113",
    "city hall san jose": "200 E Santa Clara Street, San Jose, CA 95113",
    "san jose city hall rotunda": "200 E Santa Clara Street, San Jose, CA 95113",
    "san pedro square": "87 N San Pedro Street, San Jose, CA 95110",
    "san pedro square market": "87 N San Pedro Street, San Jose, CA 95110",
    "san pedro market": "87 N San Pedro Street, San Jose, CA 95110",
    "japantown san jose": "Japantown, San Jose, CA 95112",
    "japantown": "Japantown, San Jose, CA 95112",
    "santana row": "377 Santana Row, San Jose, CA 95128",
    "downtown san jose": "Downtown San Jose, CA",
    "sofa district": "SoFA District, San Jose, CA",
    "south first area": "SoFA District, San Jose, CA",
    "willow glen": "Willow Glen, San Jose, CA",
    "communication hill": "Communication Hill, San Jose, CA",
    "coyote valley": "Coyote Valley, San Jose, CA",
}

# ---------------------------------------------------------------------------
# SCC_ABBREVIATIONS  (~80 entries)
# Scanner abbreviations and shorthand for locations.
# ---------------------------------------------------------------------------
SCC_ABBREVIATIONS: dict[str, str] = {
    # City abbreviations
    "sj": "San Jose, CA",
    "san jose": "San Jose, CA",
    "mv": "Mountain View, CA",
    "mountain view": "Mountain View, CA",
    "pa": "Palo Alto, CA",
    "palo alto": "Palo Alto, CA",
    "sc": "Santa Clara, CA",
    "santa clara": "Santa Clara, CA",
    "sv": "Sunnyvale, CA",
    "sunnyvale": "Sunnyvale, CA",
    "cup": "Cupertino, CA",
    "cupertino": "Cupertino, CA",
    "mil": "Milpitas, CA",
    "milpitas": "Milpitas, CA",
    "camp": "Campbell, CA",
    "campbell": "Campbell, CA",
    "lg": "Los Gatos, CA",
    "los gatos": "Los Gatos, CA",
    "sar": "Saratoga, CA",
    "saratoga": "Saratoga, CA",
    "la": "Los Altos, CA",
    "los altos": "Los Altos, CA",
    "mh": "Morgan Hill, CA",
    "morgan hill": "Morgan Hill, CA",
    "gil": "Gilroy, CA",
    "gilroy": "Gilroy, CA",

    # Street / location abbreviations
    "ecr": "El Camino Real",
    "el camino": "El Camino Real",
    "scb": "Stevens Creek Boulevard",
    "wsc": "West San Carlos Street, San Jose, CA",
    "mon rd": "Monterey Road, San Jose, CA",
    "mon": "Monterey Road, San Jose, CA",
    "bh rd": "Blossom Hill Road, San Jose, CA",
    "bh": "Blossom Hill Road, San Jose, CA",
    "st blvd": "Santa Teresa Boulevard, San Jose, CA",
    "cap expwy": "Capitol Expressway, San Jose, CA",
    "cap": "Capitol Expressway, San Jose, CA",
    "law expwy": "Lawrence Expressway, Santa Clara, CA",
    "law": "Lawrence Expressway, Santa Clara, CA",
    "cen expwy": "Central Expressway, Santa Clara, CA",
    "mont expwy": "Montague Expressway, Milpitas, CA",
    "mont": "Montague Expressway, Milpitas, CA",
    "alm expwy": "Almaden Expressway, San Jose, CA",
    "alm": "Almaden Expressway, San Jose, CA",
    "st expwy": "San Tomas Expressway, San Jose, CA",
    "or expwy": "Oregon Expressway, Palo Alto, CA",
    "fh expwy": "Foothill Expressway, Los Altos, CA",

    # SJPD phonetic alphabet / units
    "adam": "A (phonetic)",
    "boy": "B (phonetic)",
    "charles": "C (phonetic)",
    "david": "D (phonetic)",
    "edward": "E (phonetic)",
    "frank": "F (phonetic)",
    "george": "G (phonetic)",
    "henry": "H (phonetic)",
    "ida": "I (phonetic)",
    "john": "J (phonetic)",
    "king phonetic": "K (phonetic)",
    "lincoln phonetic": "L (phonetic)",
    "mary phonetic": "M (phonetic)",
    "nora": "N (phonetic)",
    "ocean": "O (phonetic)",
    "paul": "P (phonetic)",
    "queen": "Q (phonetic)",
    "robert": "R (phonetic)",
    "sam": "S (phonetic)",
    "tom": "T (phonetic)",
    "union phonetic": "U (phonetic)",
    "victor": "V (phonetic)",
    "william": "W (phonetic)",
    "xray": "X (phonetic)",
    "young": "Y (phonetic)",
    "zebra": "Z (phonetic)",

    # Common dispatch shorthand
    "dtsj": "Downtown San Jose, CA",
    "downtown": "Downtown San Jose, CA",
    "north san jose": "North San Jose, CA",
    "nsj": "North San Jose, CA",
    "south san jose": "South San Jose, CA",
    "ssj": "South San Jose, CA",
    "east san jose": "East San Jose, CA",
    "esj": "East San Jose, CA",
    "west san jose": "West San Jose, CA",
    "wsj": "West San Jose, CA",
    "willow glen": "Willow Glen, San Jose, CA",
    "wg": "Willow Glen, San Jose, CA",
    "evergreen": "Evergreen, San Jose, CA",
    "cambrian": "Cambrian, San Jose, CA",
    "almaden valley": "Almaden Valley, San Jose, CA",
    "berryessa": "Berryessa, San Jose, CA",
    "alum rock": "Alum Rock, San Jose, CA",
    "rose garden": "Rose Garden, San Jose, CA",
    "japantown": "Japantown, San Jose, CA",
    "jtown": "Japantown, San Jose, CA",
    "little saigon": "Little Saigon, San Jose, CA",
}

# ---------------------------------------------------------------------------
# SCC_POLICE_CODES  (~130 entries)
# 10-codes, California Penal Code sections, disposition codes, EMS codes.
# ---------------------------------------------------------------------------
SCC_POLICE_CODES: dict[str, str] = {
    # --- 10-codes ---
    "10-1": "Poor reception / unable to copy",
    "10-4": "Acknowledgment / OK",
    "10-6": "Busy / stand by",
    "10-7": "Out of service",
    "10-8": "In service",
    "10-9": "Repeat last transmission",
    "10-10": "Off duty",
    "10-11": "Animal problem",
    "10-12": "Stand by",
    "10-14": "Prowler report",
    "10-15": "Prisoner in custody",
    "10-16": "Domestic problem",
    "10-17": "Meet complainant",
    "10-19": "Return to station",
    "10-20": "Location / what is your location",
    "10-21": "Telephone call",
    "10-22": "Disregard / cancel",
    "10-23": "Arrived at scene",
    "10-25": "Report to / meet at",
    "10-27": "Driver's license check",
    "10-28": "Vehicle registration check",
    "10-29": "Check for wants/warrants",
    "10-30": "Unnecessary use of radio",
    "10-32": "Person with gun",
    "10-33": "Emergency, clear channel",
    "10-35": "Major crime alert",
    "10-36": "Correct time",
    "10-39": "Status of units",
    "10-40": "Silent run (no lights/siren)",
    "10-49": "Proceed to / en route",
    "10-51": "Drunk driver",
    "10-52": "Ambulance needed",
    "10-53": "Road blocked",
    "10-54": "Possible dead body",
    "10-55": "Coroner needed",
    "10-56": "Suicide / attempt",
    "10-57": "Hit and run",
    "10-59": "Security check",
    "10-66": "Suspicious person",
    "10-67": "Person calling for help",
    "10-70": "Fire alarm",
    "10-71": "Advise nature of fire",
    "10-72": "Structure fire",
    "10-73": "Smoke report",
    "10-80": "Pursuit in progress",
    "10-85": "Arriving at scene",
    "10-87": "Meet officer",
    "10-97": "Arrived at scene",
    "10-98": "Finished last assignment",
    "10-99": "Wanted / stolen indicated",
    "code 3": "Emergency response (lights and siren)",
    "code 4": "No further assistance needed",
    "code 5": "Stakeout",
    "code 6": "Out of car investigating",
    "code 7": "Meal break",
    "code 8": "Box alarm (fire)",
    "code 33": "Emergency, clear channel immediately",

    # --- California Penal Code sections commonly heard on scanner ---
    "187": "Homicide / murder (PC 187)",
    "207": "Kidnapping (PC 207)",
    "211": "Robbery (PC 211)",
    "215": "Carjacking (PC 215)",
    "220": "Assault with intent to commit felony (PC 220)",
    "240": "Assault (PC 240)",
    "242": "Battery (PC 242)",
    "243": "Battery on peace officer (PC 243)",
    "245": "Assault with deadly weapon (PC 245)",
    "246": "Shooting at inhabited dwelling (PC 246)",
    "261": "Rape (PC 261)",
    "273.5": "Domestic violence / corporal injury to spouse (PC 273.5)",
    "273a": "Child endangerment (PC 273a)",
    "288": "Lewd acts with minor (PC 288)",
    "290": "Sex offender registration (PC 290)",
    "314": "Indecent exposure (PC 314)",
    "415": "Disturbing the peace (PC 415)",
    "417": "Brandishing a weapon (PC 417)",
    "422": "Criminal threats (PC 422)",
    "451": "Arson (PC 451)",
    "459": "Burglary (PC 459)",
    "470": "Forgery (PC 470)",
    "484": "Theft / petty theft (PC 484)",
    "487": "Grand theft (PC 487)",
    "488": "Petty theft (PC 488)",
    "496": "Receiving stolen property (PC 496)",
    "503": "Embezzlement (PC 503)",
    "530.5": "Identity theft (PC 530.5)",
    "537": "Defrauding innkeeper (PC 537)",
    "594": "Vandalism (PC 594)",
    "597": "Animal cruelty (PC 597)",
    "602": "Trespassing (PC 602)",
    "647": "Disorderly conduct (PC 647)",
    "647b": "Prostitution (PC 647b)",
    "647f": "Public intoxication (PC 647f)",
    "653m": "Threatening phone calls (PC 653m)",
    "836": "Authority to arrest (PC 836)",
    "5150": "Involuntary psychiatric hold (WIC 5150)",
    "5150 hold": "Involuntary psychiatric hold (WIC 5150)",
    "1203.2": "Probation violation (PC 1203.2)",

    # --- Vehicle Code ---
    "vc 10851": "Vehicle theft (VC 10851)",
    "10851": "Vehicle theft (VC 10851)",
    "vc 20001": "Hit and run with injury (VC 20001)",
    "20001": "Hit and run with injury (VC 20001)",
    "vc 20002": "Hit and run property damage (VC 20002)",
    "20002": "Hit and run property damage (VC 20002)",
    "vc 23103": "Reckless driving (VC 23103)",
    "23103": "Reckless driving (VC 23103)",
    "vc 23152": "DUI (VC 23152)",
    "23152": "DUI (VC 23152)",
    "dui": "DUI (VC 23152)",
    "vc 14601": "Driving on suspended license (VC 14601)",
    "14601": "Driving on suspended license (VC 14601)",

    # --- Health & Safety Code ---
    "hs 11350": "Possession of controlled substance (HS 11350)",
    "11350": "Possession of controlled substance (HS 11350)",
    "hs 11351": "Possession for sale (HS 11351)",
    "11351": "Possession for sale (HS 11351)",
    "hs 11357": "Possession of marijuana (HS 11357)",
    "11357": "Possession of marijuana (HS 11357)",
    "hs 11550": "Under influence of controlled substance (HS 11550)",
    "11550": "Under influence of controlled substance (HS 11550)",
    "hs 11364": "Possession of drug paraphernalia (HS 11364)",
    "11364": "Possession of drug paraphernalia (HS 11364)",

    # --- Disposition / status codes ---
    "goa": "Gone on arrival",
    "utl": "Unable to locate",
    "nfr": "No further response needed",
    "att": "Attempt",
    "aro": "Area of",
    "rp": "Reporting party",
    "tc": "Traffic collision",
    "tc pio": "Traffic collision, property damage only",
    "tc inj": "Traffic collision with injuries",
    "tc fatal": "Traffic collision, fatal",
    "tc hit and run": "Traffic collision, hit and run",
    "burg": "Burglary",
    "rob": "Robbery",
    "agg assault": "Aggravated assault",
    "dom viol": "Domestic violence",
    "dv": "Domestic violence",
    "missing": "Missing person",
    "mp": "Missing person",
    "cw": "Check welfare",
    "susp circ": "Suspicious circumstances",
    "susp veh": "Suspicious vehicle",
    "susp per": "Suspicious person",

    # --- Fire / EMS Response Codes (Medical Priority Dispatch) ---
    "alpha response": "Alpha - minor, BLS ambulance",
    "bravo response": "Bravo - moderate, BLS ambulance",
    "charlie response": "Charlie - urgent, ALS ambulance",
    "delta response": "Delta - life-threatening, ALS + fire",
    "echo response": "Echo - cardiac/respiratory arrest, all units",
    "omega response": "Omega - no response needed / referral",
    "alpha": "Alpha - minor, BLS ambulance",
    "bravo": "Bravo - moderate, BLS ambulance",
    "charlie": "Charlie - urgent, ALS ambulance",
    "delta": "Delta - life-threatening, ALS + fire",
    "echo": "Echo - cardiac/respiratory arrest, all units",
    "omega": "Omega - no response needed / referral",
    "als": "Advanced Life Support",
    "bls": "Basic Life Support",
    "ems": "Emergency Medical Services",
    "working fire": "Confirmed structure fire, additional resources",
    "first alarm": "First alarm fire assignment",
    "second alarm": "Second alarm fire assignment",
    "third alarm": "Third alarm fire assignment",
    "box alarm": "Multiple units dispatched to fire",
}

# ---------------------------------------------------------------------------
# ALL_LOCATIONS  (combined geocodable location dicts)
# ---------------------------------------------------------------------------
ALL_LOCATIONS: dict[str, str] = {}
ALL_LOCATIONS.update(SCC_STREETS)
ALL_LOCATIONS.update(SCC_EXPRESSWAYS)
ALL_LOCATIONS.update(SCC_HIGHWAYS)
ALL_LOCATIONS.update(SCC_HOSPITALS)
ALL_LOCATIONS.update(SCC_SHOPPING)
ALL_LOCATIONS.update(SCC_PARKS)
ALL_LOCATIONS.update(SCC_SCHOOLS)
ALL_LOCATIONS.update(SCC_TRANSIT)
ALL_LOCATIONS.update(SCC_PUBLIC_SAFETY)
ALL_LOCATIONS.update(SCC_LANDMARKS)
